### ISSUE TITLE
Getting an OutOfMemoryException

### ISSUE THREAD

**Issue by maxvollmer** [microsoft/ApplicationInspector#103]
**Describe the bug**
I am running `AppInspector.exe analyze -s "D:\Work\HL\Half-Life VR" -f html -v TRACE` on the code in this repo: https://github.com/maxvollmer/Half-Life-VR

After about 31% it dies saying `A runtime error has occured.  Please see log file for more information.`. The log then reveals that an OutOfMemoryException was thrown while trying to load a file.  Unfortunately even with `-v TRACE` it doesn't say which file it was trying to load, probably because the exception kills the process before the file name would've been printed in the trace output.

**To Reproduce**
1. Clone https://github.com/maxvollmer/Half-Life-VR
3. Run `AppInspector.exe analyze -s "<path to where you cloned the repo>" -f html -v TRACE`

**Expected behavior**
Ideally no exception at all, and at least have `-v TRACE` print the filename before it starts doing things that might go wrong. Or when catching the exception, print the filename in the error output, so users don't need to run with TRACE at all to know which file caused an error.

I also saw that it skips files it considers too big, so maybe the threshold for this skip needs adjustment.

**Screenshots**
cmdline output:
> Microsoft Application Inspector 1.0.23
> Analyze command running
> 31% source files processedA runtime error has occured.  Please see log file for more information.

log.txt:
> 2020-01-25T11:17:17 1 ERROR - A runtime error has occured.  Please see log file for more information.
> 2020-01-25T11:17:17 1 ERROR - Runtime error: Exception of type 'System.OutOfMemoryException' was thrown.    at System.Text.StringBuilder.ToString()
>    at System.IO.StreamReader.ReadToEnd()
>    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
>    at System.IO.File.ReadAllText(String path)
>    at Microsoft.AppInspector.AnalyzeCommand.ProcessAsFile(String filename)
>    at Microsoft.AppInspector.AnalyzeCommand.Run()
>    at Microsoft.AppInspector.Program.RunAnalyzeCommand(AnalyzeCommandOptions opts)
>    at Microsoft.AppInspector.Program.<>c.<Main>b__6_0(AnalyzeCommandOptions opts)
>    at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 notParsedFunc)
>    at Microsoft.AppInspector.Program.Main(String[] args)

**Desktop:**
 - OS: Windows 10
 - Browser: NA
 - Version: NA

**Smartphone:**
 - NA

**Additional context**
NA

**Comment by guyacosta** [comment]
The code was adjusted thanks to a submission #104 to avoid trying to read excessively large files before we try to process them.  The check was occurring too late.  In addition, I now write the name of the file being processed for decompression into the log so that should help if you see it again.  Let me know if not fixed now and I'll reopen this for additional investigation.  Get the latest code or I'll be releasing an update of binaries asap.

**Comment by maxvollmer** [comment]
Awesome, thanks for the quick fix! Will test tomorrow or next weekend, and let you know how it goes.

**Comment by maxvollmer** [comment]
Just confirming that it now works like a charm. Thanks!
