### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by thawkins** [microsoft/ApplicationInspector#110]
**Is your feature request related to a problem? Please describe.**
Provide step by step instruction for installing on Windows 10 for use with Visual Studio Community.

**Describe the solution you'd like**
A clear and concise set of steps on how to install

**Comment by ggjacosta** [comment]
Thanks I'll add something to help with that. Essentially you just download the windows binary from the Releases page under the Assets section to a local directory and run the tool from there. There is no setup or installation or permissions required other than installation of .net core 3. Alternatively you can clone the repository directly from GitHub into visual studio by copying the clone URL from the code page on the right opening visual studio to a new project and using the clone option than pasting the URL into it. See the build.md for more. At that point you should be able to build source code and run it making sure to add the necessary arguments.  I will put all of this into a small instruction set for those who need it. Thanks for mentioning.

**Comment by guyacosta** [comment]
Thanks I'll add something to help with that. Essentially you just download the windows binary from the Releases page under the Assets section to a local directory and run the tool from there. There is no setup or installation or permissions required other than installation of .net core 3. Alternatively you can clone the repository directly from GitHub into visual studio by copying the clone URL from the code page on the right opening visual studio to a new project and using the clone option than pasting the URL into it. See the build.md for more. At that point you should be able to build source code and run it making sure to add the necessary arguments. I will put all of this into a small instruction set for those who need it. Thanks for mentioning.

**Comment by guyacosta** [comment]
I've added a JustRunIt.md in addition to the Build.md and tested building it in Visual Studio Community -no issues.
