### ISSUE TITLE
Provide option to disable automatic archive decompression

### ISSUE THREAD

**Issue by dstaley** [microsoft/ApplicationInspector#115]
**Is your feature request related to a problem? Please describe.**
When attempting to analyze the Chromium source code, I run into an error where the application attempts to inflate an intentionally-corrupt zip file.

**Describe the solution you'd like**
I'd like the option to pass in a flag to disable the built-in archive decompression. Alternatively, a flag to ignore files matching certain patterns.

**Comment by guyacosta** [comment]
Understood.  You do have the option today to inflate the files and scan the directory if your blocked by a corrupt zip file.  I do see how a flag to specify files to ignore will be valuable to others and will add this as an enhancement.  Thanks for the suggestion.  Note there is an existing hard list of file types that are ignored like .git mentioned in the help and wiki to be aware of.

**Comment by guyacosta** [comment]
#130 allowing you to specify what to filter.
