### ISSUE TITLE
Linux/Mac build instructions incorrect

### ISSUE THREAD

**Issue by johnmccabe** [microsoft/ApplicationInspector#119]
**Describe the bug**
The BUILD.md doc for Linux/Mac describe the build process as just running `make`, but there is no `Makefile` in the repository, either it is missing, or the document will need to be corrected.

The build instruction in the README.md works as expected.

**To Reproduce**
n/a

**Expected behavior**
Linux/Mac build process should be reproducible.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by guyacosta** [comment]
fixed.
