### ISSUE TITLE
Files exclusions seems too restrictive

### ISSUE THREAD

**Issue by heeko** [microsoft/ApplicationInspector#122]
**Describe the bug**
If your source path is containing some string that is in the `AnalyzeCommand` `_fileExclusionList` everything will be skipped.

**To Reproduce**
Run an analyze on source path like C:\Dev\CsharpTest\Foo for instance.

**Desktop (please complete the following information):**
 - OS: Windows

**Code line with the issue**
https://github.com/microsoft/ApplicationInspector/blob/1deaaa6ab6fa75827acb3f5e25bebab2481be2d0/AppInspector/Commands/AnalyzeCommand.cs#L266
In this `if` `_fileExclusionList` is checked against the entire file path `filename`. So if you have a path that contains one of the values here:
```
readonly string[] EXCLUDEMATCH_FILEPATH = "sample,example,test,docs,.vs,.git".Split(",");
```
then it will be skipped. It seems pretty common to have some "test" or "sample" as part of a folder name, at least it was for me and I only discovered why it was skipped by debbuging the app :)

**Comment by guyacosta** [comment]
There's an optional argument to disable this check see -k, --include-sample-paths.  Our goal is to ensure a high level of accuracy in reporting features in actual running code not test code or documents etc.

**Comment by guyacosta** [comment]
I wound up replacing the old restrictions with a user supplied option that's easier and more flexible.  See checkin for #130
