### ISSUE TITLE
When launching AppInspector.dll "error occurred while loading required library hostpolicy.dll" is displayed

### ISSUE THREAD

**Issue by sartajshaikahmed** [microsoft/ApplicationInspector#124]
**Describe the bug**
When launching AppInspector.dll "error occurred while loading required library hostpolicy.dll is displayed"

**To Reproduce**

1.Download "ApplicationInspector_windows_1.0.24.zip" and unzip 
2.Execute command "dotnet AppInspector.dll"

**Expected behavior**
Inspector should be launched

**Actual behavior**
Following error is displayed

Failed to load the dll from [C:\Users\sartaj.ahmed\Downloads\ApplicationInspector_windows_1.0.24\ApplicationInspector_1.0.24\hostpolicy.dll], HRESULT: 0x800700C1
An error occurred while loading required library hostpolicy.dll from [C:\Users\sartaj.ahmed\Downloads\ApplicationInspector_windows_1.0.24\ApplicationInspector_1.0.24\]

**Screenshots**
![image](https://user-images.githubusercontent.com/54312221/73437013-934ec580-4371-11ea-90ad-156192a65a44.png)

![image](https://user-images.githubusercontent.com/54312221/73437123-c7c28180-4371-11ea-9e13-1b9c110d9bed.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sartajshaikahmed** [comment]
@guyacosta I would be really thank full,  if you could provide your inputs on it. I know somewhere I am doing some silly mistake

**Comment by bilalshahzad139** [comment]
I am facing same issue. I downloaded latest release. Unziped in a folder and executed command from same folder like this 
 dotnet Appinspector.dll
It gives following error
HRESULT: 0x800700C1
An error occurred while loading required library hostpolicy.dll

I tried by providing a source code folder too but same error
dotnet Appinspector.dll analyze -s E:\myproj

I matched hostpolicy.dll version with what we've in .json file and that are matching.

**Comment by yaziid** [comment]
I faced the same problem, using Powershell weirdly works !

**Comment by guyacosta** [comment]
The error seems related to authenticode signing but the file is signed and the certificate is valid as shown in the Digital Signature for file properties.  As long as the file has not been modified etc. it should work but I'll try to reproduce it -no luck so far.  One option is to install the certificate in the file properties by selecting the signature and see if that addresses the issue.  Let me know.  I'll continue to investigate.

**Comment by bilalshahzad139** [comment]
@guyacosta I downloaded master branch, built it and tested from its bin folder and it not throwing exception and processing the files.

**Comment by guyacosta** [comment]
Good your not blocked.  I created a Windows 10 VM and downloaded the 1.0.24 release etc. and did not see an issue.  Again the signature is valid but for those having the issue there is some helpful information here in this support article indicating an AppLocker rule creation issue for that error files that have been modified from the time of signing.  I''ll continue to look for a cause for the behavior that does not fall into one of those categories a little longer.  Anyone seeing the issue on an older version of Windows -the OS was not reported and that would be helpful.

**Comment by guyacosta** [comment]
The only other related item found was you may have .net core 3.1 installed but not 3.0 which the application release and solution are targeted to.  That's why rebuilding it solved the issue for you.  I will be upgrading the solution target to 3.1.

**Comment by efriese** [comment]
What is the solution to fixing this issue? I cloned the master branch and built via "dotnet publish -c Release -r linux-x64". When I run "dotnet AppInspector.dll" from bin/publish I get the libhostpolicy.dylib missing error. This is a fresh install of .NET Core 3.1 on Catalina

**Comment by guyacosta** [comment]
See #123
