### ISSUE TITLE
Microsoft article mentioned at home page (and found in google) is missing now

### ISSUE THREAD

**Issue by birbilis** [microsoft/ApplicationInspector#132]
this link is now broken? How come?
https://www.microsoft.com/security/blog/2020/01/16/introducing-microsoft-application-inspector/

**Comment by birbilis** [comment]
in fact all the microsoft security blog seems to be down - articles on attack surface analyzer etc. also not found

**Comment by birbilis** [comment]
strange think is those articles show fine in Firefox, but in the new Chromium-based Edge (on Win10) they show:

We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available.

(sometimes they show some of the text without much formatting and with broken image icons and then they refresh to show the above message)

Also the url remains the same in the addressbar, so it's not that they redirect by mistake on Edge somewhere else.

Does it happen to others too with the new Edge?

**Comment by guyacosta** [comment]
Working fine in Edge and Chrome.  See attached.  Might be on your client only?
![MicrosoftArticle](https://user-images.githubusercontent.com/47648296/74058363-b34a3e80-499a-11ea-8029-d6f7612fb5a8.png)

**Comment by birbilis** [comment]
yep, works in Edge too now. Since that message was appearing inside the Microsoft page (wasn't a browser message), guess it was some hickup with the blog serving (had notified @microsoft on twitter so maybe they fixed it in time) and Edge managed to cache the problem and kept on showing that version for a while despite pressing refresh. Guess if I had emptied the cache it would have shown the live version again
