### ISSUE TITLE
Add a CLI parameter to disable "OpenBrowser"

### ISSUE THREAD

**Issue by Maarc** [microsoft/ApplicationInspector#133]
**Is your feature request related to a problem? Please describe.**
At the end of the analysis, ApplicationInspector opens the generated HTML file. While analysing many applications, this leads to many opened browser tabs and prevents to do something else while the tool is running.

**Describe the solution you'd like**
Providing a CLI option to disable the automatic opening of generated reports would be awesome.

**Describe alternatives you've considered**
Currently, I have rebuilt the tool on my own commenting out the "Utils.OpenBrowser(htmlOutputFilePath);" line within "LiquidWriter.cs"

**Comment by guyacosta** [comment]
Sounds good.  I also suggest using the json output if your scanning in quantities then maybe piping to a database with a search/display UI.

**Comment by Maarc** [comment]
Good point Indeed. Soon or later, I want to dig into results aggregation to have a nice overview of a wider application landscape.

**Comment by guyacosta** [comment]
Fixed with argument to suppress auto opening of browser i.e. it leaves the output.html in the directory for opening as needed.  Again, the other format options allow for opening outside of a browser also.

**Comment by guyacosta** [comment]
#145 contains the fix which will be added to the next binary release this week/asap.
