### ISSUE TITLE
Appetite for a GUI tool using Chromely or something similar?

### ISSUE THREAD

**Issue by jusso-dev** [microsoft/ApplicationInspector#135]
I'm trying to introduce non-developer/technical people in my organisation to ApplicationInspector however a lot of them can't code, and don't know how to use the CLI, I'd like to propose a simple GUI tool using Chromely.

Happy to submit a pull request and assigned this issue.

**Comment by guyacosta** [comment]
Interesting.  I'll take a PR to review.  I suspect you'll be able to get to before I do.  Let's see what you come up with.

**Comment by guyacosta** [comment]
Haven't seen a PR nor anyone else express interest so closing.
