### ISSUE TITLE
Bad internal links in the wiki

### ISSUE THREAD

**Issue by parsiya** [microsoft/ApplicationInspector#137]
**Describe the bug**
At the bottom of the main wiki page `Home.md` are two bad links to the `Rules` and `Customized Reports` sections.

**Rules**

```
Original:
[Rules](https://github.com/microsoft/ApplicationInspector/wiki/1.-Writing-Rules)

Should be (the section is named `Understanding Rules`):
[Rules](https://github.com/microsoft/ApplicationInspector/wiki/1.-Understanding-Rules)
```

**Customized Reports**

```
Original:
[Customized Reports](https://github.com/microsoft/ApplicationInspector/wiki/7.-Customized-Reports)

Should be (markdown file for customized reports is named 6.-Customized-Reports.md:
[Customized Reports](https://github.com/microsoft/ApplicationInspector/wiki/6.-Customized-Reports)
```

Github does not support pull requests for wiki, otherwise I would have made one.

It would be a good idea to use reference style links that can be updated/maintained in one place at the bottom of the page. Quick example:

```
## Custom Rules
... See this wiki for more on [Rules][rules-section] definition.

## Custom Reports
... To customize a report, see [Customized Reports][customized-reports-section].

<!-- at the bottom of the page -->
[rules-section]: https://github.com/microsoft/ApplicationInspector/wiki/1.-Understanding-Rules
[customized-reports-section]: https://github.com/microsoft/ApplicationInspector/wiki/6.-Customized-Reports
```

Things would become easier if we can use internal markdown links (e.g., `[rules-section]: 1.-Understanding-Rules.md`. I am not sure if Github wikis support such a thing.

**To Reproduce**
1. Go to https://github.com/microsoft/ApplicationInspector/wiki#custom-rules.
2. Click on the `Rules` link in the `See this wiki for more on Rules definition` sentence.
3. See the error message `You do not have permission to update this wiki.` and the page navigating back to the same page.

**Expected behavior**
"Links should go to where they should." - Unknown Pseudo-philosopher, 2020 AD.

**Comment by parsiya** [comment]
In https://github.com/microsoft/ApplicationInspector/wiki/3.-Pattern-Object-Schema

```
** Important ** if no language is specified at the parent rule level then scope at the pattern level won't be applied because there the scope type varies by language.
```

If `important` was intended to show up as bold then we should remove the spaces between the word and `**`s.

**Comment by guyacosta** [comment]
Thanks for playing editor to improve the content :).  Recently the page numbers were changed breaking some of the links that were not checked before publishing.  The suggestions are appreciated.  Ultimately, the content is not expected to change a lot so structure was not modified but the links were updated.
