### ISSUE TITLE
Update to .NET Core 3.1

### ISSUE THREAD

**Issue by gfs** [microsoft/ApplicationInspector#142]
.NET Core 3.0 end of support is March 3, 2020.  We should migrate to .NET Core 3.1 before then.

https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by guyacosta** [comment]
The tool builds and runs fine on 3.1.  Our build team @daalcant is working on fixing up our yaml pipeline to support asap.

**Comment by daalcant** [comment]
In progress.

**Comment by jusso-dev** [comment]
Just FYI, you'll break the ability to host on Windows Azure Web Apps on 3.1

**Comment by scovetta** [comment]
For Windows Azure Web Apps, ref: https://github.com/Azure/app-service-announcements-discussions/issues/129

**Comment by guyacosta** [comment]
The impact is limited -see scovetta impact.  We need to go forward due to 3.0 support EOL.

**Comment by jusso-dev** [comment]
Yep makes sense, I retract my previous statement.
