### ISSUE TITLE
F# support for Application Inspector?

### ISSUE THREAD

**Issue by Rickasaurus** [microsoft/ApplicationInspector#143]
**Is your feature request related to a problem? Please describe.**
When I saw this project I was very hopeful, there's been a big gap in the ecosystem for F# code scanning tools, and I thought this might fill it. However, it's not on the supported languages list despite being in the box in Visual Studio. 

**Describe the solution you'd like**
I would like F# support for this tool.

**Describe alternatives you've considered**
There are no security scanning tools for F# today, it's increasingly a big problem for corporate adoption. 

**Additional context**
I hope you'll seriously consider this, it would be a huge boon for the community.

**Comment by Rickasaurus** [comment]
Sorry, it looks like I was maybe wrong? "fsharp" is listed here https://github.com/microsoft/ApplicationInspector/wiki/2.1-Field:-applies_to-(languages-support)

**Comment by 7sharp9** [comment]
I would change this to no F# oriented rules are present.

**Comment by 7sharp9** [comment]
It could be the case that things like this: https://github.com/microsoft/ApplicationInspector/blob/99eceaf96377d1d1e360ac8072677c217f76e3a0/AppInspector/rules/default/os/system_registry.json#L32

Would equally apply to F#, Im expecting that there are dotnet type rules, and C#/F#/other dotnet language  specific ones.

**Comment by guyacosta** [comment]
Right.  A lot of rules are applicable to multiple languages so the "applies_to" value is empty in those cases and the rules engine will search for matches in any of the supported language file types.  Languages that have one or more specific and distinct patterns for a given action/feature/cmd do need to have separate ones defined for them.  It's possible some of the patterns for csharp would apply to F# and the applied_to could have it added to the array.  If you see a few of those, send a specific issue for it.  Would love to have someone familiar with F# do that else we will get around to it and other more languages specific patterns soon.
