### ISSUE TITLE
Wrong links in the wiki

### ISSUE THREAD

**Issue by parsiya** [microsoft/ApplicationInspector#150]
**Describe the bug**

#### Instance 1
https://github.com/microsoft/ApplicationInspector/wiki/2.1-Field:-applies_to-(languages-support)

Bottom of the page has a bad link in `languages.json.txt`

```
To see the language data file and type designation see languages.json.txt
```

* Link goes to: https://github.com/microsoft/ApplicationInspector/files/4093510/languages.json.txt
* Should go to: https://github.com/microsoft/ApplicationInspector/blob/master/RulesEngine/Resources/languages.json

**To Reproduce**
1. Go to https://github.com/microsoft/ApplicationInspector/wiki/2.1-Field:-applies_to-(languages-support).
2. Scroll down to the bottom of the page.
3. Click on the `languages.json.txt` link.
4. See that is does not go to the correct place.

#### Instance 2
https://github.com/microsoft/ApplicationInspector/wiki/2.2-Field:-tags-(features)

Last paragraph has a link that is not in the markdown format (and is not rendered). The link is a missing an extra `)` to close the link source.

What we have

```
See the
[applies_to](https://github.com/microsoft/ApplicationInspector/wiki/2.1-Field:-applies_to-(languages-support) section ....
```

Should be (adding a extra `)` to the end of the link):

```
See the 
[applies_to](https://github.com/microsoft/ApplicationInspector/wiki/2.1-Field:-applies_to-(languages-support)) section ....
```

**To Reproduce**
1. Go to https://github.com/microsoft/ApplicationInspector/wiki/2.2-Field:-tags-(features)
2. Scroll down to the bottom of the page.
3. See the not-rendered link.

**Screenshots**
![image](https://user-images.githubusercontent.com/3981231/75723703-a666f500-5c91-11ea-82ee-30efbac65aa6.png)

### Expected behavior
"Clicking a hyperlink is about the destination, not the journey." - Abraham Lincoln

**Comment by guyacosta** [comment]
Love the quote. Fixed and thank you.  Checking all other links...
