### ISSUE TITLE
False Positive: ".target" => matches ".tar"

### ISSUE THREAD

**Issue by scovetta** [microsoft/ApplicationInspector#153]
**Describe the bug**
rules/default/data_handling/compressed_files.json

The rule looks for \.tar. It should probably be \.tar\b or maybe regex-word.

(Using 1.0.27.)

**Comment by guyacosta** [comment]
This fix will be merged.

**Comment by guyacosta** [comment]
Note the issue was a duplicate pattern with no clear value one had the -word break the first one did not.  Retested solution with change successfully.
