### ISSUE TITLE
NuGet Command Pkg Install Doesn't Copy Default Rules to Local App

### ISSUE THREAD

**Issue by guyacosta** [microsoft/ApplicationInspector#163]
**Describe the bug**
After installing the Microsoft.CST.ApplicationInspector.Command pkg and running the containing app, the calls fail due to the default rules folder missing from where the dll is copied to i.e. the containing app \bin\debug or \bin\release folders causing an exception.  A default or custom rules path is expected.  The caller wanting to use the default ruleset would have to copy them manually from the nuget install location locally into their local app bin folder

**To Reproduce**
1. Download the pkg from Nuget via Visual Studio into an app
2. Create a AnalyzeCommandOption object
3. Create an AnalyzeCommand object
4. Call GetResults method on the command object.  See the exception from step 3.

**Expected behavior**
User does not have to manually copy over the Rules folder into their bin folders for use.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by guyacosta** [comment]
@daalcant let me know if a code change is required apart from the nuget packaging to resolve.  I'm looking into also.

**Comment by gfs** [comment]
My recommendation is to have default rules be built and accessed as embedded resources so you don't have to include separate files with the library.

-------- Original Message --------

**Comment by gfs** [comment]
From [Attack Surface Analyzer](https://github.com/microsoft/AttackSurfaceAnalyzer/blob/master/Lib/Utils/Analyzer.cs) this is how I load the default rules and analysis json files.

```
            try
            {
                var assembly = typeof(FileSystemObject).Assembly;
                var resourceName = "AttackSurfaceAnalyzer.analyses.json";

                using (Stream stream = assembly.GetManifestResourceStream(resourceName))
                using (StreamReader reader = new StreamReader(stream))
                {
                    config = JsonSerializer.Deserialize<RuleFile>(reader.ReadToEnd());
                    Log.Information(Strings.Get("LoadedAnalyses"), "Embedded");
                }
                if (config == null)
                {
                    Log.Debug("No filters today.");
                    return;
                }
            }
```

**Comment by gfs** [comment]
Since your rules are formatted similar to DevSkim we can pack them before inclusion using something like we do in the devskim csproj.

```
  <Target Name="PreBuild" BeforeTargets="BeforeCompile">
    <Exec Command="dotnet ../../RulePacker/devskim.dll pack ../../rules Resources/devskim-rules.json" />
  </Target>
```

We can probably reuse the same RulePacker (just a devskim.dll) implementation here.

**Comment by guyacosta** [comment]
Yeah, I think so.  I had planned that earlier but we thought we could achieve using packing / unpacking alone and users would then be able to see/edit the rules files directly but if that work work will use that approach.

**Comment by guyacosta** [comment]
Inprogress...

**Comment by gfs** [comment]
Users should still be able to see the rules files in the source code. I think probably a few documented examples of rules might be valuable as well vs. just a drop of all the rules.

**Comment by daalcant** [comment]
This will also require a change to the Commands csproj to remove the rule packaging reference. @guyacosta let me know if there's a branch for this issue that I can contribute to.

**Comment by guyacosta** [comment]
The solution is similar to DevSkim our sister project.  It adds a PackRules command what combines them into a single file under the Resources folder as an embedded file so we can avoid having to rely on an external separate module.  When a rule(s) is modified, the user runs the PackRules -d command to update the default embedded file and it is checked in as part of the project.  When the pipeline or local build command rules the updated file is readded to the ApplicationInspector.Commands.dll which is used to get the resource as a stream.  @@daalcant, I removed the older rules folder packing since it didn't result in what we needed so I think we're good.  Solution is tested under various use cases and works removing the dependency on the local file system.

**Comment by guyacosta** [comment]
Still ironing out the kinks in the PR.  Stay tuned.
