### ISSUE TITLE
Bug: OutOfMemory Exception When Creating the JSON Output

### ISSUE THREAD

**Issue by parsiya** [microsoft/ApplicationInspector#166]
**Describe the bug**
When running ApplicationInspector on a codebase that results in a big report, creating the JSON file results in an exception of type `System.OutOfMemory`.

**To Reproduce**
1. Run ApplicationInspector on a target that creates a large report with `-v debug` flag.
    * In my case I am running it on 600-700MBs of C/C++ code,
2. Notice the error message in the log file after it crashes in the end.

**Error Messages**

Command prompt

```
96% source files processedDecompressing files...
Decompressing files...
100% source files processed
Preparing report
A runtime error has occured.  Please see log file for more information.
```

From the log file with `-v debug`

```
2020-03-13T19:45:12 1 ERROR - Runtime error: Exception of type 'System.OutOfMemoryException' was thrown.    at System.Text.StringBuilder.ToString()
   at System.IO.StringWriter.ToString()
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Microsoft.AppInspector.LiquidWriter.WriteApp(AppProfile app)
   at Microsoft.AppInspector.AnalyzeCommand.FlushAll()
   at Microsoft.AppInspector.AnalyzeCommand.Run()
   at Microsoft.AppInspector.Program.RunAnalyzeCommand(AnalyzeCommandOptions opts)
   at Microsoft.AppInspector.Program.<>c.<Main>b__6_0(AnalyzeCommandOptions opts)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 notParsedFunc)
   at Microsoft.AppInspector.Program.Main(String[] args)
````

**Expected behavior**
Not crash. I have downloaded a lot of RAM.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1903

**Comment by gfs** [comment]
@parsiya Per line 47 of LiquidWriter.cs the this crash is when the full JSON is being stuffed in the HTML output - it is not separately generating a JSON output, so I don't think that a switch for #167 would do anything here.

@guyacosta worth investigating another JSON parsing library? I've been using https://github.com/neuecc/Utf8Json. Its not too complex to replace Newtonsoft.Json with it.

**Comment by guyacosta** [comment]
The JSON is not being stuff into html they are two separate writers the liquid writer than merges template html and data for the html and separately a jsonwriter which just serializes the results.  I have a warning note for html reports loading that are too large but I'll look into this issue and maybe the alternate json lib.  Should have something later today for it.

**Comment by gfs** [comment]
If that is the case why not serialize directly to a stream to disc rather than serializing in memory and then later writing to disc?

-------- Original Message --------

**Comment by guyacosta** [comment]
That may work depending how the library functions i.e. if it allocates memory for the process rather than accepting the file stream as it's only output buffer.  It if still does it's work in mem then returns that as a stream to be written to disk it won't but I will look into that first i.e. something like one of these methods:
// serialize JSON to a string and then write string to a file
File.WriteAllText(@"c:\movie.json", JsonConvert.SerializeObject(movie));

// serialize JSON directly to a file
using (StreamWriter file = File.CreateText(@"c:\movie.json"))
{
    JsonSerializer serializer = new JsonSerializer();
    serializer.Serialize(file, movie);
}

Thanks for mentioning.  I'll get back to you both.

**Comment by gfs** [comment]
I know utf8json is designed to be low/zero allocation and will stream to the stream rather than building in memory. I can't imagine newtonsoft is any different.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by guyacosta** [comment]
Solution serializes directly to the file stream now for json writer.  Note the utf8json while significantly better for performance if left unstructured requires use of the PrettyPrint method which only accepts a byte[] not an <T> object hence would require conversion to a string first anyway and not help.  I did note the html output does actually require the AppProfile object to be converted to json for access in the AppInspector.js files for HTML UI so there is a conversion that is needed there and I'm unable to work around that so if you need HTML based output size has some memory limitations but json or text should work fine now.

**Comment by gfs** [comment]
I believe that the pretty print method prints a json string prettily. It doesn't do something with an arbitrary byte[]. The base serialization output in utf8json is a byte[].

-------- Original Message --------

**Comment by parsiya** [comment]
Thanks, I will try the new build on the code base again tomorrow.

**Comment by parsiya** [comment]
I tried the app on the same code base and there is no OOM exception anymore. For the record, the resulting JSON is 300MBs. Thanks for fixing the issue.

**Comment by guyacosta** [comment]
That's good to hear we addressed the bug.  The file size is large and dependent on the source scanned of course.  I will think about whether to add an option to remove the excerpt info and just leave the line info in the match details to reduce size.
