### ISSUE TITLE
Feature: Switch to Disable JSON File Creation

### ISSUE THREAD

**Issue by parsiya** [microsoft/ApplicationInspector#167]
**Is your feature request related to a problem? Please describe.**
When creating an html report, the JSON output is ALWAYS created except when the output format is text. Currently, with a big report the JSON file results in a crash. See #166. Skipping the JSON file will be stopgap measure.

**Describe the solution you'd like**
A command line switch to disable JSON file creation.

**Describe alternatives you've considered**
* The `text` format does not have the issue above but it's not really what I want.
* I considered not using ApplicationInspector, but I like ApplicationInspector.

**Comment by guyacosta** [comment]
The json is a feature allowing the user to switch from the UI so not planning on an option to disable today and as mentioned in #166 this doesn't really solve the problem if for instance a large json only format was specified.  Going to close this and focus on fixing #166.  Thanks.

**Comment by parsiya** [comment]
Thanks. Makes sense.
