### ISSUE TITLE
Cannot use the `-r` option multiple times

### ISSUE THREAD

**Issue by parsiya** [microsoft/ApplicationInspector#172]
**Describe the bug**
The readme mentions we can use the `-r` switch multiple times. 

```
Add custom rules (can be specified multiple times)
  dotnet ApplicationInspector.dll analyze -s /home/user/myproject -r /my/rules/directory -r /my/other/rules
```

The executable does not allow this.

```
ApplicationInspector_1.1.16>
ApplicationInspector.CLI.exe analyze -s c:\path\to\source -r c:\path\to\rules\1 -r c:\path\to\rules\2
Microsoft Application Inspector 1.1.16+7824e5a0e0
ApplicationInspector.CLI 1.1.16+7824e5a0e0
c Microsoft Corporation. All rights reserved.

ERROR(S):
  Option 'r, custom-rules-path' is defined multiple times.
```

**To Reproduce**
1. Run the following command.
    1. `ApplicationInspector.CLI.exe analyze -s c:\path\to\source -r c:\path\to\rules\1 -r c:\path\to\rules\2`
2. Note the error message.
    1. `ERROR(S): Option 'r, custom-rules-path' is defined multiple times.`

**Expected behavior**
Be able to use the `-r` switch multiple times as mentioned in the readme.

**Desktop:**
 - OS: Windows 10 Pro
 - Version: 1903

**ApplicationInspector**
 - Version: 1.1.16 from the release page.

**Comment by guyacosta** [comment]
In this case I'm going to update the readme as the ease in which someone can isolate their custom rules into one folder doesn't warrant a code change to support an array of possible locations to read from which would entail more cost/testing than benefit.  The multiple custom path functionality was removed long ago and the readme was simply outdated.  Thanks for finding this!

**Comment by parsiya** [comment]
Thanks for responding quickly.
