### ISSUE TITLE
Crash while analyzing apps with embedded "tgz" files. ("Length cannot be less than zero")

### ISSUE THREAD

**Issue by Maarc** [microsoft/ApplicationInspector#193]
**Describe the bug**
ApplicationInspector crashes while analysis applications embedding ".tgz" files.

**To Reproduce**
1. Open a terminal
2. Create a dummy application archive with an embedded ".tgz" file like this:
`mkdir a; cd a; echo "test" > a.java; tar -cvzf a.tgz a.java; zip -r b.jare a.tgz a.java; zip -r a.war *; cd ..; mv a/a.war .; rm -Rf a/`
3. Let ApplicationInspector analyze the application.
4. It will crash the analysis with the following error:

```
Problem while decompressing /FOLDER1/a.war/a.tgz: Unzip and try running on uncompressed files
Length cannot be less than zero. (Parameter 'length')
Additional details may be found in log file at /FOLDER2/ApplicationInspector_1.1.30/log.txt
```
Content of `/FOLDER2/ApplicationInspector_1.1.30/log.txt`:
```
2020-04-07T12:50:23 1 ERROR - AppInsLog - Problem while decompressing /FOLDER1/a.war/a.tgz: Unzip and try running on uncompressed files
2020-04-07T12:50:23 1 ERROR - AppInsLog - Length cannot be less than zero. (Parameter 'length')
```

**Expected behavior**
Analysis should go on and either ignore the embedded `*.tgz` file or extract it and analyze what is inside.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: MacOS Catalina

**Additional context**
This should probably corrected in `AppInspector/Commands/AnalyzeCommand.cs`

**Comment by Maarc** [comment]
PS: I used `ApplicationInspector_netcoreapp_1.1.30.zip` to run AppInspector.

**Comment by guyacosta** [comment]
I do like the idea to continue the analysis with subsequent files...maybe have a max fail cap before quitting.  We do run into files whose structure is not compatible with our libraries and will try to start submitting a few identified issues to get them addressed there as well.  Will look into this and get back to you.

**Comment by guyacosta** [comment]
Found the issue.  It was in how we were creating the file name for the item not with the decompression .  Filenames smaller than 3 characters e.g. "a.tgz" were not handled right.  A fix is on the way for that issue and will look the continue option on error.
