### ISSUE TITLE
Compile Regexes and Cache them for performance

### ISSUE THREAD

**Issue by gfs** [microsoft/ApplicationInspector#205]
Each call to the regex constructor is expensive as the constructor has to parse the string into its logical regex representation.  If you want maximum performance out of each call to the regex you also want to use `RegexOptions.Compiled` which further increases that cost.

Creating a new regex object for each call to match pattern like in `TextContainer.cs` is very expensive. https://github.com/microsoft/ApplicationInspector/blob/71df07821b3ce7c9b4c5fe77ac4c7e56c68f4c78/RulesEngine/TextContainer.cs#L161 

Instead the `SearchPattern` when created should have a compiled regex inside of it.

.NET 5 Has extra improvements for compiled regexes (and normal regexes) as well. https://devblogs.microsoft.com/dotnet/regex-performance-improvements-in-net-5/

**Comment by guyacosta** [comment]
@gfs will do.  Thanks for catching.
