### ISSUE TITLE
Requesting Unique Tags may result in an incomplete list of tags

### ISSUE THREAD

**Issue by gfs** [microsoft/ApplicationInspector#207]
**Describe the bug**
If you have Rule One with Tags `A` and `C`  and Rule Two with Tags `A` and `B`. 
If `unique tags only` is on and
* Rule One matches first: Two will not match and results will not be tagged with `B`.
* Rule Two matches first, One will not match and the results will not be tagged with `C`.

In #204 we parallelize the analysis so the order rules are applied becomes non-deterministic and you will get either behavior 1 or 2 above at random.

**To Reproduce**
Pass appropriate values to `UniqueTagsCheck` if any of the tags passed in are included in the set of known tags all tags will be ignored. https://github.com/microsoft/ApplicationInspector/blob/6375d1d73c594645e7eb863e03b6c4bed5164f1a/RulesEngine/RuleProcessor.cs#L324
**Expected behavior**
Requesting unique tags should return all matched tags, deduplicated.

**Proposed Fix**
We should check if there are any new tags and grab them, rather than checking for duplicate tags and discarding everything.

**Comment by guyacosta** [comment]
in-progress
