### ISSUE TITLE
Unable to add Microsoft.CST.ApplicationInspector.Commands package

### ISSUE THREAD

**Issue by guyacosta** [microsoft/ApplicationInspector#223]
This may be getting addressed already but wanted to track the bug.  Am unable to add or update to the latest package due to reference changes in MultiExtractor.

Error	NU1101	Unable to find package MultiExtractor. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org	ConsoleApp1	C:\Users\guacosta\source\repos\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj	1

**Comment by gfs** [comment]
Fixed by #222.
