### ISSUE TITLE
Support Statement Clarification

### ISSUE THREAD

**Issue by daalcant** [microsoft/ApplicationInspector#228]
We are piloting a new support statement, to make it clear to repo users where/how to ask questions about the usage of the software in this repo.  Our goal is to eventually have a statement like this in most repos.  Do you have any feedback about the statement?  Please share it here.

**Comment by guyacosta** [comment]
@daalcant -is this completed?

**Comment by daalcant** [comment]
Keeping this open for a couple weeks in case we receive feedback.

**Comment by daalcant** [comment]
Closing due to lack of feedback.
