### ISSUE TITLE
Programming languages output has build and other file types

### ISSUE THREAD

**Issue by jacobmsft** [microsoft/ApplicationInspector#255]
Programming Language: package.json, javascript, html, yaml
There is a package.json in the programming languages list, which seems like an artifact and doesn't make sense to be there.

**Comment by guyacosta** [comment]
@jacobmsft we scan solution, project and config files as well so strictly speaking Programming Language as a label and var should be changed to be all encompassing like "Scan File Types" or something to be more representative of what is included.  I'll look at updating.  Don't want to change the schema too much to avoid impacting users but can make it a target to correct/enhance in the near future.
