### ISSUE TITLE
HTML Report Not Loading Correctly for NuGet CLI Install Option

### ISSUE THREAD

**Issue by gfs** [microsoft/ApplicationInspector#264]
### Steps:
` appinspector analyze -s /path/to/some/code`

### Expected:
Formatted Report

### Result:
Result is not formatted and is missing all images.

### Version:
`ApplicationInspector.CLI 1.2.49+c4843d26aa`

![image](https://user-images.githubusercontent.com/98900/90180071-4bb6e680-dd63-11ea-9742-2191c78242db.png)

**Comment by gfs** [comment]
The fix was reverted so this is presumed live again.

**Comment by guyacosta** [comment]
See comments in #266 which indicates the problem is seen when installing the CLI from nuget but not when downloading and building and running.  The solution for the path must work for both.  Unclear where the defect was introduced but will be addressing so works either way asap/today.

**Comment by guyacosta** [comment]
The issue occurs when a user installs the CLI using the Nuget.org shown option "dotnet tool install --global Microsoft.CST.ApplicationInspector.CLI --version 1.2.5x" which places the bulk of the files under <user>\.dotnet\tools\.store\microsoft.cst.applicationinspector.cli\1.2.52\microsoft.cst.applicationinspector.cli\1.2.52\tools\netcoreapp3.1\any.  This install location is where the DLL's and html subfolder are placed.  **Note** the repetition in the directory structure for related enhancement opportunity.  

If the user tries to run the application using the global convenience file "AppInspector.exe"<args> located in the <user>\.dotnet\tools folder ** far above the any folder and runs it from some location** other than then "any" folder, the application is unable to locate it's html subdirectory resources  Running it or the full command i.e. dotnet applicationinspector.cli.dll<args> from the any folder works without issue.

Resolution request to @daalcant :
1. address the directory install structure to simplify and reduce duplication 
2. place the appinspector.exe in the same directory as the bulk of the binary files and update the PATH on install accordingly
3. submit a PR on the tested changes

**Comment by gfs** [comment]
I'm not sure the proposed resolution is possible. We package the nuget with nuget pack and dotnet decides where to place the binaries when unpacking it.

**Comment by guyacosta** [comment]
Looking at the Pack command and config options control of output structure doesn't look available :(.  I had hoped only for an intermediate solution using that approach to get it working again asap until I complete the work in #241 to aggregate all html dependencies into one file.  The output file when run by default is placed in the ...<users> directory for some reason.  Would have expected maybe ...dotnet\tools where appinspector.exe lands.  I could search subdirectories to find the html folder and set the path in the index.html etc. files but I'll work on completing #241 instead today and have partial implementation already.
