### ISSUE TITLE
Icons for features that are not present should be grayed out

### ISSUE THREAD

**Issue by gfs** [microsoft/ApplicationInspector#266]
**Describe the bug**
Icons are not being grayed out when they are not present.

**To Reproduce**
Get patch from #265 first to ensure resources are loaded.

**Expected behavior**
Icons for properties that don't apply should be gray not blue.

**Screenshots**
![image](https://user-images.githubusercontent.com/98900/90181733-c6810100-dd65-11ea-98e4-480d72e16230.png)

**Comment by guyacosta** [comment]
The issue was in the #265 branch/PR itself.  The original code base was fine and the PR should not have been approved on closer inspection.  The main branch is now affected and I'm reverting it back i.e. #265 will not be accepted closing this issue.

**Comment by guyacosta** [comment]
The core in Main has been restored and tested to work properly again showing the layout using the CSS and other resources under the html subfolder and icons that are properly active or grayed out.  @gfs in the future suggest we evaluate a PR and comment on it with the PR and only submit bugs against main branch.  Having believed there was an issue as reported that #265 was fixing I approved the PR too quickly (my bad) but there was no issue prior to PR that I can detect on either the layout or the icons.  Thanks.

**Comment by gfs** [comment]
This reproduced only after the fix in the PR. However main did *not* work. David and I have both reproduced https://github.com/microsoft/ApplicationInspector/issues/264 *before* 265. 

Main without #265 does not work.

**Comment by gfs** [comment]
Also. I didn't open the PR. And you were the one who merged it.

**Comment by guyacosta** [comment]
Strange I do not see either issue until #265 is added and have cleaned off code locally to restart fresh.  I agree on who merged and if you were both seeing on main before submitting the bug makes sense but the resources are located for now under the html subdirectory and that must be included in the path in index.html etc.  I'll get to bottom and contact you directly to verify the problem.

**Comment by gfs** [comment]
I reproduced this by installing directly from the nuget and running "appinspector" on the command line. Can you repro that way?

**Comment by guyacosta** [comment]
Ah yes.  When it is run from Visual Studio it works correctly which was my testing method.  Thank you I will look into this so that it works properly again for both.  The install info was helpful.

**Comment by guyacosta** [comment]
When I applied the PR #265 it no longer worked from Visual Studio etc.  I'll fix it.  Interesting how it got broken as it was working sometime recently in both but I'll track it down.

**Comment by guyacosta** [comment]
While #264 is now understood and being treated, I'm unable to reproduce the icon non-deactivation that you have shown above in either the 1.2.52 or 1.2.53 builds and install using Nuget command i.e. dotnet tool install --global Microsoft.CST.ApplicationInspector.CLI --version 1.2.53 when the tool is run from the dotnet install folder (see comments in #264 for current bug limitation).  Nor can I reproduce it by building the code and running it.  @gfs If you can try to isolate when this is happening that would be appreciated.

**Comment by gfs** [comment]
Looks like this is resolved.
