### ISSUE TITLE
Leaving output default gives warning about lacking html extension

### ISSUE THREAD

**Issue by gfs** [microsoft/ApplicationInspector#276]
**Describe the bug**
If you run analyze with default settings (to get an output.html file) you get a warning that your output file name doesn't have .html.  This isn't really an error, as you see later the default created file ends up being output.html in the end, so we never had to specify .html.
![image](https://user-images.githubusercontent.com/98900/91922854-d3698400-ec83-11ea-8367-928fc320807a.png)

This warning should only appear if the user has specified a new name that doesn't have the extension, not for the default name.

**Comment by guyacosta** [comment]
fix is ready and will be pushed in a few minutes thanks
