### ISSUE TITLE
Tag issues found analyzing OAT

### ISSUE THREAD

**Issue by gfs** [microsoft/ApplicationInspector#277]
**Describe the bug**
I ran Application Inspector over OAT and found a number of false positives.

**To Reproduce**
1. Get OAT.
2. Use latest AppInspector `analyze -s OAT/`
3. See Results

** Incorrect Results **
* Authentication: OAuth
* Authentication: General
* Authorization: Roles Based Access Control
* Hash Algorithm: SHA 256
* Encryption: General
* OS Dynamic Execution: Missing C# Scripting
* Data: Access Credentials

Then, Use latest AppInspector `analyze -s OAT/OAT/`
** Incorrect Results **
OS Dynamic Execution: Missing C# Scripting
Reflection?

**Comment by guyacosta** [comment]
Will correct thanks for the bug.

**Comment by guyacosta** [comment]
Output now from latest build 1.2.70 is corrected and now 100% accurate:
      "Cryptography.HashAlgorithm.General",
      "Data.Parsing.JSON",
      "Data.Serialization",
      "Dependency.SourceInclude",
      "Framework.Development.Logging.Serilog",
      "Framework.Development.Microsoft.Linq",
      "Metadata.Application.Author",
      "Metadata.Application.Description",
      "Metadata.Application.Name",
      "Metadata.Application.Output.Type",
      "Metadata.Application.Target.Framework",
      "Metadata.Application.Version",
      "Metadata.CloudServices.Code.Repo.GitHub",
      "Metadata.CloudServices.Code.Repo.Microsoft.NuGet",
      "Metadata.Development.Build.VisualStudio",
      "Metadata.Platform.Microsoft.NETStandard",
      "Metadata.Platform.OS.Microsoft.WindowsStandard",
      "Miscellaneous.OpenSourceLicense.MIT",
      "OS.Process.Multiprocessing"
