### ISSUE TITLE
Automatically highlight the line with finding, not the first line of the snippet

### ISSUE THREAD

**Issue by gfs** [microsoft/ApplicationInspector#278]
For example, in the following the SerializeObject line is the found line, and should be highlighted.  Highlighting the first line is confusing as it draws attention to the context rather than the actual finding.

![image](https://user-images.githubusercontent.com/98900/91923853-352aed80-ec86-11ea-83ca-c91548fdd9c7.png)

**Comment by guyacosta** [comment]
Fixed finally
