### ISSUE TITLE
Looking for defaultRulesPkd.json in wrong directory

### ISSUE THREAD

**Issue by scovetta** [microsoft/ApplicationInspector#284]
**Describe the bug**
When packing default rules, the tool winds up (in my case) looking in C:\Users\AppInspector\Resources\defaultRulesPkd.json, which is definitely incorrect:

**To Reproduce**
```
PS C:\Users\scovetta\Downloads\ApplicationInspector_windows_1.2.34\ApplicationInspector_1.2.34> .\ApplicationInspector.CLI.exe packrules -d -o out.json
output file argument ignored for -d option
Invalid file or directory C:\Users\AppInspector\Resources\defaultRulesPkd.json
Additional details may be found in log file at C:\Users\scovetta\Downloads\ApplicationInspector_windows_1.2.34\ApplicationInspector_1.2.34\appinspector.log.txt
```

**Expected behavior**
The output file should be placed in a location in the current directory, and the rules should be pulled from the appropriate location. If packrules isn't meant to be used in a release (meaning, it's a dev-time tool), then that should be documented and the error should reflect that.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] n/a
 - Version [e.g. 22]: 1.2.34

**Additional context**
n/a

**Comment by guyacosta** [comment]
The current version is a lot newer 1.2.62 but the problem is valid in that the packrules -d option really is intended as a build time tool where the raw rules are expected.  Note the packrules -r <custom-rule-path> -o <output-path> works fine.  I'll get an update for the documentation and error message.  Thanks for catching.

**Comment by guyacosta** [comment]
Fixed.  New error message: "Unable to locate local default rules folder.  This command is intended to be run as part of the source code build operation only.  Use the custom rules option instead."
