### ISSUE TITLE
Tagcounters.json no longer being picked up for custom reporting?

### ISSUE THREAD

**Issue by marc-patterson** [microsoft/ApplicationInspector#286]
**Description**
Following the documentation [here](https://github.com/microsoft/ApplicationInspector/wiki/6.-Customized-Reports), I wanted to see detail of Classes and Functions in the reports, so I created this tagcounters.json file in the preferences directory:

```
[
    {
      "tag": "Metric.Code.Class.Defined",
      "displayName": "Classes",
      "includeAsMatch": true
    },
    {
      "tag": "Metric.Code.Function.Defined",
      "displayName": "Functions",
      "includeAsMatch": true
    },
    {
      "tag": "Metric.Code.Exception.Caught",
      "displayName": "Exceptions",
      "includeAsMatch": true
    },
    {
      "tag": "Metric.Code.HTMLForm.Defined",
      "displayName": "Forms",
      "includeAsMatch": true
    },
    {
      "tag": "Dependency.SourceInclude",
      "displayName": "Dependencies",
      "includeAsMatch": false
    },
    {
      "tag": "Miscellaneous.CodeHygiene.Comment.Todo",
      "displayName": "Comments",
      "includeAsMatch": false
    },
    {
      "tag": "Miscellaneous.CodeHygiene.Comment.Fix",
      "displayName": "Fix-comments",
      "includeAsMatch": true
    },
    {
      "tag": "Miscellaneous.CodeHygiene.Comment.Suspicious",
      "displayName": "Suspicious-comments",
      "includeAsMatch": true
    },
    {
      "tag": "Metric.Code.Logging.Call",
      "displayName": "Logging Calls",
      "includeAsMatch": false
    },
    {
      "tag": "Metric.Code.URL",
      "displayName": "URL's",
      "includeAsMatch": false
    }
  ]
```
and then added this to tagreportgroups.json:
```
      {
        "title": "Code Metrics",
        "dataRef": "CodeMetrics",
        "patterns": [
          {
            "searchPattern": "Metric.Code.Logging.Call",
            "displayName": "Code Logging",
            "detectedIcon": "fab fa-dev"
          },
          {
            "searchPattern": "Metric.Code.Class.Defined",
            "displayName": "Class Defined",
            "detectedIcon": "fab fa-dev"
          },
          {
            "searchPattern": "Metric.Code.Exception.Caught",
            "displayName": "Exception Caught",
            "detectedIcon": "fab fa-dev"
          },
          {
            "searchPattern": "Metric.Code.URL",
            "displayName": "Code URL",
            "detectedIcon": "fab fa-dev"
          },
          {
            "searchPattern": "Metric.Code.Function.Defined",
            "displayName": "Function Defined",
            "detectedIcon": "fab fa-dev"
          }                                       
        ]
      } 
```
Running an analysis results in the custom Code Metrics section being added to the report, but no results for Class Defined or Function Defined are shown. 

Furthermore on the Summary - Tag Counters screen, it displays:

- Metric.Code.Function.Defined: Count: 119 Include as Match: false
- Metric.Code.Class.Defined - Count: 18 Include as Match: false

So it appears to be picking up the customisations in tagreportgroups.json, but not in tagcounters.json.

**Screenshots**
<img width="677" alt="Screenshot 2020-09-15 at 17 06 17" src="https://user-images.githubusercontent.com/60782923/93235725-db422180-f775-11ea-9d02-16214494a606.png">
<img width="1101" alt="Screenshot 2020-09-15 at 17 05 56" src="https://user-images.githubusercontent.com/60782923/93235734-de3d1200-f775-11ea-94c2-e820c1222374.png">

**Desktop**
 - macOS Catalina
 - Google Chrome v85
 - Application Inspector v1.2.63

**Comment by guyacosta** [comment]
Ah yes there is code to exclude "Metric" tags from the report which are deemed non-essential i.e. the purpose of the primary report on the HTML UI features page is...features not metrics.  They will continue to appear in the Summary Tag Counters page.  Any non-metric tags and associated rules including custom ones will appear in the features section as designed.  I will update the wiki for additional clarity about this.  Thanks for asking.

**Comment by guyacosta** [comment]
Updated page to clarify.

**Comment by gfs** [comment]
Guy I'm not sure this is working correctly.  From the two screenshots we see that Tag Counters found, for example, 118 matches for Function Defined, but the first screenshot has no confidence, N/A and no light up for function defined.  What does the indicator in the first screenshot mean if its not related to these numbers in the second one?

**Comment by guyacosta** [comment]
Metrics are not supported in the Feature UI page hence the partial result.  I suppose I can fix that and block them from appearing at all.  I'll reopen as a bug but will not be displaying metrics on that page.

**Comment by guyacosta** [comment]
Basically, each Metric or counter is excluded from the details match results only the tag is counted but because the tag was added to the UI group it partially appears with no data...

**Comment by guyacosta** [comment]
Final comment to help explain that an early design decision not include include metrics in the detailed report is that they would appear as noise throughout the json report with each instance taking up space when we just want a count.  Again, the primary purpose is to identify features.  The exclusion of these from the detailed matches is what creates the empty data rows in the features page today because we didn't intend for them to appear here, only the tag counters area.  Hope that helps.

**Comment by guyacosta** [comment]
One other change that was made a few versions back is we no longer need the tagcounters.json to define the behavior to automatically count anything with the tag section containing "metric" and not include it in the detailed reports.  Looks like my documentation didn't get updated which is part of the reason for the confusion so I've corrected that in the [tags](https://github.com/microsoft/ApplicationInspector/wiki/3.5-Tags) section of the wiki and in the [custom report](https://github.com/microsoft/ApplicationInspector/wiki/6.-Customized-Reports)s section.

**Comment by marc-patterson** [comment]
Thanks for taking the time to reply, and for updating the docs. 

In my opinion it's a shame that the option to include metrics in the detailed report was removed, as we'd find this information useful in our use case.

**Comment by guyacosta** [comment]
The information is still available just not on the "features" page which represents functionality only and is tied to the detailed matches in the report.  I do understand it's just in this case there is a design/intent conflict but hope you enjoy the tool and can make use of the counters info found on the summary subpage of the html report and in the json/text formats.

**Comment by guyacosta** [comment]
Detection and warning added to log.  Final doc updated.
