### ISSUE TITLE
Secure Secrets Detection

### ISSUE THREAD

**Issue by Jayp0weru5r** [microsoft/ApplicationInspector#287]
**Is your feature request related to a problem? Please describe.**

Identify secure secrets security features that are in use. Eg Azure KeyVault, HashiCorp Vault,  etc..

**Describe the solution you'd like**

When an application is using a secure secrets solution it is identified in the Security Features.

Basically it would target on keywords like VaultSharp, KeyVault, HashiCorp, etc.. 
**Describe alternatives you've considered**
None at this time

**Additional context**

For assessment of applications if they are using a secure secrets solution this can help to identify these patterns.

**Comment by guyacosta** [comment]
done thanks for submitting

**Comment by Jayp0weru5r** [comment]
Great thanks for incorporating
