### ISSUE TITLE
Unrendered HTML character codes in HTML reports

### ISSUE THREAD

**Issue by Maarc** [microsoft/ApplicationInspector#297]
**Describe the bug**
While using the latest version of the Application Inspector, the generated HTML reports contain a lot of not rendered HTML codes (e.g. & lt; & quot; ...) on the following pages: Project info, Metadata ... and in the "Source File Listings". The corresponding characters should replace the HTML codes.

**To Reproduce**
1. Download and unpack AppInspector 1.2.69
2. Download and unzip the source code of AppInspector as test-application
3. Execute a full analysis of the downloaded application
`dotnet ${MAI} analyze -s ${APP} -b false -v Info -x high -c high,medium -k lib,.vs,.git,.idea`
4. Open the Summary -> Project Info / Summary -> Metadata / Features -> Click a feature -> click on an associated rules

**Expected behavior**
No un-rendered HTML codes should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/2445024/94003586-b5cb9e00-fd9b-11ea-92a2-a57a7ce08d30.png)
![image](https://user-images.githubusercontent.com/2445024/94003594-ba905200-fd9b-11ea-9385-a6cc9f333849.png)
![image](https://user-images.githubusercontent.com/2445024/94003613-c54ae700-fd9b-11ea-850a-f8fa9081a8ad.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser: Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by guyacosta** [comment]
Thanks for catching this.  Must be a side effect of recent changes that wasn't caught -didn't see and will correct this asap.

**Comment by guyacosta** [comment]
fixed
