### ISSUE TITLE
Identify Infrastructure as Code (Terraform, Chef, Puppet,Ansible)

### ISSUE THREAD

**Issue by Jayp0weru5r** [microsoft/ApplicationInspector#299]
**Is your feature request related to a problem? Please describe.**
When assessing content in a repo it would be a nice feature to also identify infrastructure as code in use.

**Describe the solution you'd like**
Possibly a new category for IAC identifiers That include Azure ARM templates, Terraform, Packer, Ansible

**Describe alternatives you've considered**
Instead of new category add to an existing category related to DevOps or build.

**Additional context**
Thinking at the concept of unified pipelines it would help to Also identify infrastructure as code and other infrastructure configurations.

**Comment by guyacosta** [comment]
I like it.

**Comment by guyacosta** [comment]
Support is added for ARM, Hashicorp Terraform and Packer.  No required/common distinguishable features in script code could be identified for Ansible, Chef or Puppet from other types of files.

**Comment by guyacosta** [comment]
The fix will be in the next release.
