### ISSUE TITLE
Bump JS dependencies

### ISSUE THREAD

**Issue by scovetta** [microsoft/ApplicationInspector#303]
**Describe the bug**
Reminder to bump JS dependencies (bootstrap, jQuery, c3/d3, etc.) and their associated CSS files.

**Comment by guyacosta** [comment]
Note the D3 lib can not be updated at this time as it causes functional loss of UI.  Other updates were successful.

**Comment by scovetta** [comment]
Sounds good, we'll revisit next time we do a version bump. No vulnerabilities in d3, so we're fine staying on a slightly older version for a while.
