### ISSUE TITLE
Nugets being published with full version

### ISSUE THREAD

**Issue by gfs** [microsoft/ApplicationInspector#306]
**Describe the bug**
Nuget packages for application inspector are being published with the full version including the commit hash after the dash.  This triggers nuget.org into thinking it is a pre-release package and it is thus unavailable if you just call regular install.

**To Reproduce**
1. Go to https://www.nuget.org/packages/Microsoft.CST.ApplicationInspector.CLI/1.2.83-ge9290d303a
2. See how versions have extra after dash starting a few releases ago

**Comment by guyacosta** [comment]
@daalcant let me know if you have time to investigate this week or not and I'll jump in.

**Comment by daalcant** [comment]
I don't see any changes that should have caused this problem. I'll investigate this week.

**Comment by daalcant** [comment]
Fixed, found a pipeline error. Latest version is now 1.2.77 as expected.
