### ISSUE TITLE
As an ApplicationInspector user I'd like the output filenames for json and html to be unique so the prior output files aren't overwritten

### ISSUE THREAD

**Issue by cqueern** [microsoft/ApplicationInspector#328]
**Is your feature request related to a problem? Please describe.**

When I write my output.html file it overwrites the earlier created output.html file if I've not manually renamed it.

**Describe the solution you'd like**

I'd like it if the prior html file were not overwritten by a newly performed scan.

**Describe alternatives you've considered**

Perhaps the filename is something different than simply output.html. Elements such as these may be added to the output filename to make it more unique:

* timestamp
* input filename

**Additional context**
N/A

**Comment by gfs** [comment]
Thanks for the suggestion. This is a great idea and we will implement it but I can’t give a timeline right now.

**Comment by gfs** [comment]
I checked the options we have and you can accompilish this today with the -o flag.

For example 
`appinspector analyze -s path/to/foo -o foo-report.html`
`appinspector analyze -s path/to/bar -o bar-report.html`

**Comment by cqueern** [comment]
Ah ha! I see it now in the [CLI Usage page of the wiki](https://github.com/microsoft/ApplicationInspector/wiki/1.-CLI-Usage). Thank you!
