### ISSUE TITLE
Optimized logo png

### ISSUE THREAD

**Issue by cqueern** [microsoft/ApplicationInspector#330]
**Is your feature request related to a problem? Please describe.**
The logo.png file is not optimized to reduce unnecessary data transfer.

**Describe the solution you'd like**
The logo.png file should be optimized to reduce unnecessary data transfer.

**Describe alternatives you've considered**
N/A

**Additional context**
The attached version of the logo.png file was optimized with kraken.io and ImageOptim and reduces the filesize from 3.96kb to 2.2kb with no visible impact on image quality.

![icon-128](https://user-images.githubusercontent.com/1588185/112251638-a681bc00-8c29-11eb-94c1-7d15cdf766e0.png)

**Comment by gfs** [comment]
Thanks for your suggestion. I'll consider this in the next PR.
