### ISSUE TITLE
Custom Rule Format

### ISSUE THREAD

**Issue by lilsedg** [microsoft/ApplicationInspector#331]
Can you provide a custom rule format? I have a list of Regexes I would like to add as a custom rule. Is there an appropriate format the rule file must be in? 
"Rule parsing failed for file /My/Custom/File/Path/CustomRule.json"

**Comment by gfs** [comment]
The most likely culprit for this is malformed JSON.

There's documentation on the Wiki but it doesn't have an explicit example.  Your best bet is to look at the default rules and refer to the wiki and then change the rule to do what you want. 

Here's an example.  Say you want to find any `foo` in code and any `bar` in comments.

This is a valid rule file with one default rule:
```
[
  {
    "name": "Cryptography: x.509 Certificate Use",
    "id": "AI006200",
    "description": "Cryptography: x.509 Certificate Use",
    "tags": [
      "Cryptography.X509Certificates.Use"
    ],
    "severity": "moderate",
    "patterns": [
      {
        "pattern": "x509|\\.(crt|cer|spc|p7b|p7s|p7r|ca-bundle)",
        "type": "regex-word",
        "scopes": [
          "code"
        ],
        "modifiers": [ "i" ],
        "confidence": "high",
        "_comment": "do not include pfx or pem see rule below for x509 client auth"
      },
      {
        "pattern": "PKCS|PaddingMode|SubjectIdentifier|Certificate",
        "type": "regex",
        "scopes": [ "code" ],
        "confidence": "high",
        "modifiers": [ "i" ],
        "_comment": ""
      }
    ]
  }
]
```
This is the modified rule:
```
[
  {
    "name": "Detects foo or bar",
    "id": "YourId",
    "description": "Detects Foo Or Bar",
    "tags": [
      "Detection.FooOrBar"
    ],
    "severity": "moderate",
    "patterns": [
      {
        "pattern": " foo ",
        "type": "regex",
        "scopes": [
          "code"
        ],
        "modifiers": [ "i" ],
        "confidence": "high",
        "_comment": "This is case insensitive"
      },
      {
        "pattern": " bar ",
        "type": "regex",
        "scopes": [ "comment" ],
        "confidence": "high",
        "_comment": "this is case sensitive"
      }
    ]
  }
]
```

If you have some custom rules that appear to meet this criteria you can share them and perhaps I can point out the error.  Have you tried using the verify rules command to see if there is additional information available.

**Comment by lilsedg** [comment]
Thanks! This is exactly what I needed, my file was in the wrong format.
