### ISSUE TITLE
AppInspector timing out Azure Pipeline

### ISSUE THREAD

**Issue by rajbansjoshi** [microsoft/ApplicationInspector#336]
We have AppInspector integrated to our Azure pipeline and lately we have observed that the pipeline fails as the appsinpector takes more than an hour to run. 

Following is the error that we see:-

##[error]The job running on agent Hosted Agent ran longer than the maximum time of 60 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134

Is there anyone else facing this issue??

**Comment by gfs** [comment]
Hi Rajbansjoshi,

How large is your codebase?  Which version of application inspector are you using?

**Comment by rajbansjoshi** [comment]
@gfs we are using version, 1.2.100 and the codebase size is 72 kb.

**Comment by gfs** [comment]
Thanks for the additional information. 

If you can share the target you’re scanning with me that would be the easiest way for me to identify what’s happening.

 If that’s not possible you can add more verbosity which might tell you what file it’s stuck on. Try adding these arguments “ --single-threaded -x high -v Trace”

**Comment by gfs** [comment]
@rajbansjoshi were you able to rerun with higher verbosity to identify which file it is stalling on?

**Comment by gfs** [comment]
@rajbansjoshi We have a beta of 1.3 available on the development branch.  Can you reproduce this issue by building 1.3 from source?  We plan to have a binary release available within a month.

**Comment by gfs** [comment]
RC for 1.3 is now available and have had no action on this.  Please test again with 1.3 and if the issue reproduces open a new issue.

**Comment by gfs** [comment]
Note that AppInspector 1.3 has options for setting and overall or per file timeout as well.
