### ISSUE TITLE
Per file timeout

### ISSUE THREAD

**Issue by gfs** [microsoft/ApplicationInspector#342]
Allow a per file processing timeout argument to prevent runaway analysis.

**Comment by scovetta** [comment]
#344 Looks good, just a rendering bug when outputting timeout messages (the progress bar gets a little broken).

![image](https://user-images.githubusercontent.com/732166/117051283-399f1e80-accb-11eb-829f-95b9ac534e7d.png)

**Comment by gfs** [comment]
Fixed by adding a pause to console output when running the progress bar.
