### ISSUE TITLE
Duplicate results after version 1.2.89 cause error in file dialog

### ISSUE THREAD

**Issue by ggjacosta** [microsoft/ApplicationInspector#345]
Changes since version 1.2.89 are causing duplication results to be included and shown in the file details dialog causing multiple results to be shown and the reported line number to be wrong except for the last listed file when selected.

The default behavior as specified in the help is to report only one instance of a match using either the best match or first match options.  The current behavior doesn't adhere to that anymore causing the UI to be misleading and confusing.

Steps:
Run the analyze command against a large project where more than one match for a given feature may be found.
View the results on the Key Features page and select a rule result on the right to open the file dialog
See there are more than one file listings shown
See the line number is not correct until the last file entry is selected

Expected:
Only one result is shown in the file dialog and the line number is correct

**Comment by gfs** [comment]
We are removing the first vs last match functionality in the next release so fixing that is not a priority.

The line number issue will be addressed though.

**Comment by gfs** [comment]
Removed the incorrect line number at the bottom in #347.  The line number for each match is shown obviously when you click on the result.

**Comment by gfs** [comment]
Thanks for the catch Guy!

**Comment by gfs** [comment]
If you have any ideas for 1.3, development is happening on the development branch and there's an open PR right now with a rewrite of the analyze command.
