### ISSUE TITLE
Unknown language file types like .png's are included after version 1.2.89

### ISSUE THREAD

**Issue by ggjacosta** [microsoft/ApplicationInspector#346]
Since version 1.2.89 unknown file types not specified in the languages.json for the rulesengine like .png, lock, .json, .css, .tmpl, .plantuml and others are included in the scan and scan results and not recorded in the log file as skipped.  The result is that more false positives are now winding up in the results.

One example is a match from a binary image file e.g. .png which clearly is not intended as a code detected faeture.

Expected:
Unknown file types which don't match a predefined language or build file type are automatically excluded from scan results and logged.

**Comment by gfs** [comment]
Won't fix.  There are rules that apply regardless of language or build file type.  If you want to ignore files add them to the ignore patterns.  If you have a suggestion for the default ignore pattern I'm happy to update that.
