### ISSUE TITLE
Rule file (rust.json) has a weird high-ascii header

### ISSUE THREAD

**Issue by scovetta** [microsoft/ApplicationInspector#352]
**Describe the bug**
The rust.json file doesn't parse correctly (via Python, .NET might be more lenient). Either way, it has a 0xEF 0xBB 0xBF header before the first bracket:

![image](https://user-images.githubusercontent.com/732166/117244173-6d726500-aded-11eb-9576-052aa4b2efad.png)

This was found in the main branch.

**Comment by gfs** [comment]
Fixed in development branch.
