### ISSUE TITLE
Rules with "sub-string" vs "substring" pattern types

### ISSUE THREAD

**Issue by scovetta** [microsoft/ApplicationInspector#353]
**Describe the bug**
Noticed a few rules have "sub-string" vs. most others that have "substring". Not sure if App Inspector handles them both gracefully, but they should all be the same (probably substring).

* [frameworks/java.json](https://github.com/microsoft/ApplicationInspector/blob/main/AppInspector/rules/default/frameworks/java.json)
* [frameworks/ruby.json](https://github.com/microsoft/ApplicationInspector/blob/main/AppInspector/rules/default/frameworks/ruby.json)

**Comment by gfs** [comment]
Fixed in development branch.
