### ISSUE TITLE
Excessively large generated report files

### ISSUE THREAD

**Issue by Maarc** [microsoft/ApplicationInspector#378]
**Describe the bug**
Since you updated to .NET 5, the generated report files (JSON & HTML) became very very large.

**To Reproduce**
1. Retrieve https://github.com/OrchardCMS/OrchardCore as a test application (git clone)
2. Analyze the repo `dotnet ApplicationInspector.CLI.dll analyze -s "/folder/to/OrchardCore" -v Info -x high -c high,medium -k lib,.vs,.git,.idea`
3. You will obtain one 611MB-large HTML file and one 564MB large JSON file

**Expected behavior**
With AppInspector 1.2.89 (version I keep using) the same files had a size of around 3 MB. 

**Desktop**
 - OS: macOS BigSur 11.3.1 (20E241)
 - Version: App Inspector 1.3.17 dotnet_core distribution (leveraging dotnet 5.0.203)

**Comment by gfs** [comment]
Thanks for your report. 

One note: Starting with 1.3 the -k option uses glob patterns so it's likely not excluding what you expect. For a folder use '**/foldername/**' as we only enumerate files not folders. 

It shouldn't be outputting both an html and a JSON from a single run, which I will investigate. 

Thank you for providing the source your using. I will try a run against the sample project you provided.

**Comment by gfs** [comment]
I've also added an argument that works will with `-t` to not gather extra metadata about individual files with `-n`.

Running `dotnet .\bin\Debug\net5.0\ApplicationInspector.CLI.dll analyze -s  C:\Users\gstocco\Documents\GitHub\OrchardCore -k **/lib/**,**/.vs/**,**/.git/**,**/.idea/** -f json --no-show-progress --file-timeout 0 -v debug -o out2.json -t` the output is less than 3mb.

**Comment by gfs** [comment]
1.3.4 was just released and fixes a bug with the `-t` option.

**Comment by Maarc** [comment]
Hi @gfs !

Thanks again for your support.

I just conducted a few tests with the latest 1.4.2 release.

### (A) Using `-t`

Indeed, using the `-t` option tremendously shrunk the file, back to less than 3 MBs. However, the leveraged features are no more highlighted on the the "Application features" page:

![image](https://user-images.githubusercontent.com/2445024/122226285-1ebcee00-ceb6-11eb-9132-7a7800d7a1f8.png)

and no tag is listed into the "Report Summary -> Tags List View" page:

![image](https://user-images.githubusercontent.com/2445024/122226433-44e28e00-ceb6-11eb-91e7-e0a55967c4e0.png)

To see the features used, I would need to open every feature group and look manually:

![image](https://user-images.githubusercontent.com/2445024/122226390-398f6280-ceb6-11eb-8bb6-d6afb95f122e.png)

Thus, the `-t` option is not really usable for me yet. 


### (B) Using `-t` and `--context-lines`

When I add `-n`, the generated file is 3MB smaller, but the "Report Summary -> Project info -> Analyzed files" diagram is broken: 

![image](https://user-images.githubusercontent.com/2445024/122229971-81fc4f80-ceb9-11eb-9a58-0fd3fcd24f07.png)

The file's size is around 15MB, which is great.


### (C) Using `--context-lines`

I ended upgrading to the version 1.4.2 and using the `--context-lines 0` option. The generated file is around 17MB, which is still a lot, but better than the >600MB I had before.


____


Should I file issues for (A) and (C)?

**Comment by gfs** [comment]
> ### (A) Using `-t`
> Indeed, using the `-t` option tremendously shrunk the file, back to less than 3 MBs. However, the leveraged features are no more highlighted on the the "Application features" page:

This is a bug.

> and no tag is listed into the "Report Summary -> Tags List View" page:
> 

This is also a bug. I have a fix for this. #383.

> ### (B) Using `-t` and `--context-lines`
> When I add `-n`, the generated file is 3MB smaller, but the "Report Summary -> Project info -> Analyzed files" diagram is broken:

That's expected.  Its no longer gathering that data so there's nothing to show.

> ### (C) Using `--context-lines`
> I ended upgrading to the version 1.4.2 and using the `--context-lines 0` option. The generated file is around 17MB, which is still a lot, but better than the >600MB I had before.
> 
> Should I file issues for (A) and (C)?

C doesn't sound like a bug.

**Comment by Maarc** [comment]
Thank you for your answer!

Sorry, I meant (A) and (B), not (A) and (C).

**Comment by gfs** [comment]
A will be fixed when I can address #384.

B will probably not be addressed until the redo of the interface in #2.
