### ISSUE TITLE
NuGet Package Depends on Non-Existent Package

### ISSUE THREAD

**Issue by scovetta** [microsoft/ApplicationInspector#386]
**Describe the bug**
Our NuGet package (https://www.nuget.org/packages/Microsoft.CST.ApplicationInspector.Commands) depends on "AppInspector.Common", which doesn't exist as a standalone NuGet. It's included in the package itself.

**To Reproduce**
1. `dotnet new console`
2. `dotnet add package Microsoft.CST.ApplicationInspector.Commands`

```
PS C:\dev\source\g> dotnet add package Microsoft.CST.ApplicationInspector.Commands
  Determining projects to restore...
  Writing C:\Users\miscovet\AppData\Local\Temp\tmpA89A.tmp
info : Adding PackageReference for package 'Microsoft.CST.ApplicationInspector.Commands' into project 'C:\dev\source\g\g.csproj'.
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/microsoft.cst.applicationinspector.commands/index.json
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/microsoft.cst.applicationinspector.commands/index.json 5145ms
info : Restoring packages for C:\dev\source\g\g.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/appinspector.common/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/appinspector.common/index.json 226ms
error: NU1101: Unable to find package AppInspector.Common. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
error: Package 'Microsoft.CST.ApplicationInspector.Commands' is incompatible with 'all' frameworks in project 'C:\dev\source\g\g.csproj'.
```

**Expected behavior**
We probably don't want .Common to be a dependency, since the DLL is included in the distribution.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Version: 1.4.3

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by daalcant** [comment]
Looks like the project reference doesn't have the correct tags to bundle the .Common DLL into the package.
