### ISSUE TITLE
Detect matches in build files (like pom.xml) only works if the tag contains Metadata

### ISSUE THREAD

**Issue by ismadirolas** [microsoft/ApplicationInspector#400]
**Is your feature request related to a problem? Please describe.**
We are trying to create a custom rule that detects dependencies of our libraries in pom.xml or package.json. The rule looks like:
`{
      "name": "Our Framework: Java",
      "id": "OU000000",
      "description": "Our Framework: Java",
      "applies_to": [ "pom.xml" ],
      "tags":[ "Our.Framework.Java" ],
      "severity": "moderate",
      "patterns": [
        {
          "pattern": "our-framework",
          "type": "string",
          "scopes": [ "all" ],
          "modifiers": ["i"],
          "confidence": "high"
        }
      ]
    }`

But this rule never matches anything. I read in the documentation (https://github.com/microsoft/ApplicationInspector/wiki/3.5-Tags) that this rule will only work if the tag name contains Metadata. In fact, there are some buit-in rules that will never match anything like:
`{
    "name": "Development: Build Tool (Maven)",
    "id": "AI016800",
    "description": "Development: Build Tool (Maven)",
    "applies_to": [ "pom.xml" ],
    "tags": [ "Development.Build.Maven" ],
    "severity": "moderate",
    "patterns": [
      {
        "pattern": "Maven",
        "type": "regex",
        "scopes": [ "code", "comment" ],
        "modifiers": [ "i" ],
        "confidence": "high"
      }
    ]
  }` 
in https://github.com/microsoft/ApplicationInspector/blob/main/AppInspector/rules/default/frameworks/build.json

**Describe the solution you'd like**
I think that if a rule explicitly applies to a build-type file (like pom.xml), it should match even if the Tag doesn't contains Metadata, maintaining the restriction for rules that applies to other languages.

**Comment by gfs** [comment]
I'm not sure I understand why this distinction is in place but it does not seem to be the right approach to me either.

I'll take a closer look at what it would take to support regular tags in "build" files.

**Comment by gfs** [comment]
https://github.com/microsoft/ApplicationInspector/blob/4ce91639d6d6c9a74685030afa604ed9c78c247e/RulesEngine/RuleProcessor.cs#L155

Here is the comment describing the rationale for this behavior.

I'm not sure that I agree with this behavior but I'm not sure if it's better to add an option to enable build file rules.

**Comment by ismadirolas** [comment]
Hi @gfs, I understand that it is good to avoid false positives inside long json or yaml config files for example, but i think when the rule explicitly try to match with this kind of files (or other "build" files) it should works, I think adding a condition that when the rule has a "build" type of file in "applies_to" field, avoid this behavior maybe?

**Comment by gfs** [comment]
> I think adding a condition that when the rule has a "build" type of file in "applies_to" field, avoid this behavior?

This might be a good solution.

**Comment by gfs** [comment]
Upon further examination, it looks like I had already implemented this functionality in the library but it was not bubbled up to the CLI.

See #401 which adds the `allow-all-tags-in-build-files` or `A` option to output all tag results from build files during an analysis.

**Comment by gfs** [comment]
> Hi @gfs, I understand that it is good to avoid false positives with long json or yaml config files for example, but i think when the rule explicitly try to match with this kind of files (or other "build" files) it should work, I think adding a condition that when the rule has a "build" type of file in "applies_to" field, avoid this behavior? Thanks for the answer!

I did investigate implementing this, but the code that checks for scopes does it based on individual conditions and is more generic, but the check that is done if it is a "build" file is done later after the scopes have already been checked and is done at the rule level - which may have multiple conditions with different scopes declared in each.

**Comment by gfs** [comment]
Please try the new build with the `-A` argument to see if this resolves your issues.

**Comment by ismadirolas** [comment]
It works. Thanks a lot @gfs !
