### ISSUE TITLE
Process Metric as a counter if the word is at the end of the tag.

### ISSUE THREAD

**Issue by ismadirolas** [microsoft/ApplicationInspector#406]
**Is your feature request related to a problem? Please describe.**
A tag with “Metric” is supposed to be processed like a counter, but we’ve notice that we need a dot after “Metric” for that to happen, so a tag "OurProject.Metric.OurModule" works as a counter, but "OurProject.OurModule.Metric" will be processed as a feature.

**Describe the solution you'd like**
We think that it could be interesting to make tags ending with "Metric" behave as a counter, so when we make insights of them, we can group by levels as we do with the features, for example, in the previous case, we can visualize all metrics grouped by "OurProject.OurModule".

**Comment by gfs** [comment]
Thanks for your report. 

I believe that this This should be an easy fix:

This line should actually be splitting the string on '.' And checking if any of the components me are `Metric`. The other cases in this block are similarly a bit suspect and need similar treatment. 

https://github.com/microsoft/ApplicationInspector/blob/860d9009b4f4295a3b96afbc129bd9d8f3d5f1d7/AppInspector/MetaDataHelper.cs#L85

**Comment by gfs** [comment]
I think the original intention was that metrics would all be specified and look like `Metric.Foo`, `Metric.Bar`.  I don't think there's a particularly compelling reason to keep that restriction so #395 also changes this to support `Metric` being any portion of the tag.
