### ISSUE TITLE
Add a way to detect if a file exists.

### ISSUE THREAD

**Issue by ismadirolas** [microsoft/ApplicationInspector#410]
**Is your feature request related to a problem? Please describe.**
We want to make a rule that detects if a file exists in the filesystem, because it would be related to a functionality itself (for example, if we detect a tsconfig.json named file, we can infer that the project uses Typescript)

**Describe the solution you'd like**
One solution would be using the "applies_to_file_regex" field, but if the rule hasn't patterns to match, it will generate one match for each file that exists with this name o regex name. For example, a rule like this:

`{
  "name": "Typescript",
  "id": "TEST0001",
  "description": "Typescript",
  "tags":[ "Test.Product.Typescript" ],
  "severity": "critical",
  "applies_to_file_regex": [ "tsconfig.json" ]
}` 

will generate one match in the result like this:
`{
    "ruleId": "TEST0001",
    "ruleName": "Typescript",
    "ruleDescription": "Typescript",
    "tags": [
      "Test.Product.Typescript"
    ],
    "severity": "Critical",
    "pattern": "",
    "confidence": "",
    "type": "",
    "language": "json",
    "fileName": "./tsconfig.json",
    "sample": "",
    "excerpt": "",
    "startLocationLine": 0,
    "startLocationColumn": 0,
    "endLocationLine": 0,
    "endLocationColumn": 0
  }`

In order to generalize the behaviour, it would work with "applies_to" field too, and will generate one match for each file of the types setted in appplies_to field. For example, a rule without patterns that "applies_to": "json", will generate one match for each json file detected.

We are open to other solutions of course.

Thanks a lot! regards.

**Comment by gfs** [comment]
I believe you can accomplish this by adding "Metric" into your tag names. This will then instead gather a count of the matches instead of the actual matches. 

https://github.com/microsoft/ApplicationInspector/wiki/3.5-Tags#counters

**Comment by gfs** [comment]
Metadata is probably the feature you want to leverage here. 

You seem to not care where this was identified just that it was (at least in this example).

**Comment by gfs** [comment]
I'm taking a look at the code and don't see how the metadata bit functions as described in the wiki. 

Metric should be working fine.

**Comment by gfs** [comment]
After more consideration I do not think it makes sense to rewrite how metadata tags works.  I think that using metric tags provides you with the data you want.

For example if I modify your rule above to read:
```
[{
  "name": "Test Rule",
  "id": "ID0001",
  "description": "Test Rule",
  "tags":[ "Metric.Application.Yaml.File" ],
  "severity": "critical",
  "applies_to_file_regex": [ "application.yml" ],
  "patterns": [
    {
      "pattern": "main",
      "type": "regex",
      "scopes": [ "all" ],
      "modifiers": [],
      "confidence": "high"
    }
  ]
}]
```

And an `application.yml` file that just contains `main`.

I then get the following result:
```
{
  "appVersion": "Microsoft Application Inspector 1.4.15+7b161f5d9e",
  "resultCode": 0,
  "metaData": {
    "applicationName": "C:\\Path\\To\\application.yml",
    "sourcePath": "C:\\Path\\To\\application.yml",
    "sourceVersion": null,
    "authors": null,
    "description": null,
    "lastUpdated": "1/4/2022 7:28:38 PM",
    "dateScanned": "1/5/2022 5:05:15 PM",
    "totalFiles": 1,
    "filesTimedOut": 0,
    "filesAnalyzed": 1,
    "filesSkipped": 0,
    "filesAffected": 1,
    "filesErrored": 0,
    "totalMatchesCount": 0,
    "uniqueMatchesCount": 0,
    "packageTypes": [],
    "appTypes": [],
    "uniqueTags": [],
    "uniqueDependencies": [],
    "outputs": [],
    "targets": [],
    "OSTargets": [],
    "fileExtensions": [
      "yml"
    ],
    "cloudTargets": [],
    "CPUTargets": [],
    "languages": {
      "yaml": 1
    },
    "tagCounters": [
      {
        "tag": "Metric.Application.Yaml.File",
        "count": 1
      }
    ],
    "detailedMatchList": [],
    "filesInformation": [
      {
        "FileName": ".\\application.yml",
        "ScanTime": "00:00:00.0727928",
        "Status": "Affected",
        "NumFindings": 1,
        "ModifyTime": "2022-01-04T19:28:38.0758091Z",
        "CreateTime": "2022-01-04T19:28:37.8707905Z",
        "AccessTime": "2022-01-06T01:04:51.3497893Z"
      }
    ]
  }
}
```

**Comment by ismadirolas** [comment]
Hi, thanks for the answer.
You are right, we can cover de example use case with metrics, but still we have a problem with one use case, it is when the file is empty, there is no way to detect its existence with a pattern because if we set the pattern value as "pattern": "", there will be no matches, but still we need some way to detect the existence of the file... We try to with ".*" pattern but we need at least one blank space in the file to get the match (or increase the tagCounter in case of Metric). 
I don't know if there is a easy way to accomplish this use case. For example, if the pattern is empty (""), increase the counter anyway without compiling and executing the pattern...

I know it is a weird use case, but we use this kind of files in our projects as markers to auto generate code, and maybe it could be useful in other scenarios.

**Comment by gfs** [comment]
Good to hear we have already covered one case. 

For this second empty file case, have you tried using `^$` as the regex?

**Comment by gfs** [comment]
> Good to hear we have already covered one case.
> 
> For this second empty file case, have you tried using `^$` as the regex?

I tested this and while the regex is valid we had a separate check that was skipping empty files. #413 will change this to allow rules to be checked against empty files.

**Comment by ismadirolas** [comment]
Hello @gfs ,
We can cover our use case with this solution, we tested it and it works. Thanks for the quick solution!
