### ISSUE TITLE
applies_to_file_regex field in rules with wildcard is not working

### ISSUE THREAD

**Issue by ismadirolas** [microsoft/ApplicationInspector#417]
**Describe the bug**
We want to detect matches in yaml files but only inside a folder, so we think we can use applies_to_file_regex with a wildcard like the documentation says: [3.6-Matching-File-Names](https://github.com/microsoft/ApplicationInspector/wiki/3.6-Matching-File-Names) but it seems to not work.

**To Reproduce**
With a rule like this:
`{
  "name": "Github: Actions",
  "id": "GITHUB000001",
  "description": "Github Actions",
  "applies_to_file_regex": [
    ".github/workflows/*.yml"
  ],
  "tags": [
    "GitHub.CI.Actions.Workflows"
  ],
  "severity": "moderate",
  "patterns": [
    {
      "pattern": "custom-actions",
      "type": "string",
      "scopes": [
        "code"
      ],
      "confidence": "high"
    }
  ]
}`

We don't have any match.
We don't have either with "*.yml", but we have the matches with "applies_to": "yaml", or if we put in "applies_to_file_regex" the complete route of a file, for example, ".github/workflows/our-workflow.yml", we get the match too, so we think that the problem is with the wildcard.

Thanks in advance.

**Comment by gfs** [comment]
`/*` matches any number of slashes.

You want something like `path/to/.*.yml`

**Comment by ismadirolas** [comment]
I understand. It works with the correct regex.
But then you should update the documentation that talks about wildcards, it's a little confused.

Thanks a lot for the answer!

**Comment by gfs** [comment]
I see how the wiki was misleading. I've updated it to clarify it uses regular expressions.
