### ISSUE TITLE
Add custom extensions in analysis execution.

### ISSUE THREAD

**Issue by ismadirolas** [microsoft/ApplicationInspector#418]
**Is your feature request related to a problem? Please describe.**
We want to add some languages to https://github.com/microsoft/ApplicationInspector/blob/main/RulesEngine/Resources/languages.json list, like css or .md files, in order to reduce the number of unknown file types in our projects.
We can make a PR if the languages are worldwide known (like css or markdown), but we think it might be interesting if the CLI allows to add a custom json file with the same format with more file extensions in executions with a new cli parameter.

**Comment by gfs** [comment]
This is an interesting idea. 

Would you want to append to the languages or replace them?

**Comment by ismadirolas** [comment]
Hi @gfs ,

I think it is a better idea to replace them to have more control over languages.

**Comment by gfs** [comment]
@ismadirolas 

I took a quick look and currently languages are being handled by a static class that implicitly loads the embedded languages. Once those become changeable it being static isn't great. 

I think it would be better if we are going to allow customized languages to instead make that an instance class that is used by the rule processor (which it itself an instance class). 

I'm fully booked at least this week but I'll see if I can knock it out within the next few weeks.

**Comment by gfs** [comment]
This is available in 1.5, which will be published shortly. @ismadirolas
