### ISSUE TITLE
"search_in" : "finding-region(0,0)" in Condition fails verfyrules command.

### ISSUE THREAD

**Issue by jamongcandy** [microsoft/ApplicationInspector#429]
**Describe the bug**
The wiki says [default is "finding-region(0,0)"](https://github.com/microsoft/ApplicationInspector/wiki/3.3.-Condition-Object-Schema#schema), 
but
`"search_in" : "finding-region(0,0)"` in Condition fails verfyrules command.

**To Reproduce**
myRule.json file
```json
[
    {
        "id": "SA000005",
        "name": "Testing.Rules.MallocAndFree0",
        "tags": [
            "Testing.Rules.MallocAndFree0"
        ],
        "severity": "Critical",
        "description": "this rule aims to find malloc() and free() at the same line(just for testing purpose)",
        "patterns": [
            {
                "pattern": "malloc\\(",
                "type": "regex",
                "confidence": "High",
                "modifiers": [
                    "i"
                ],
                "scopes": [
                    "code"
                ]
            }
        ],
        "conditions": [
            {
                "pattern": {
                    "pattern": "free\\(",
                    "type": "regex",
                    "scopes": [
                        "code"
                    ],
                    "modifiers": [
                        "i"
                    ]
                },
                "search_in": "finding-region(0,0)",
                "negate_finding": false
            }
        ],
        "_comment": ""
    }
]
```

terminal
```sh
$ appinspector verifyrules -r myRule.json                                  
Verify Rules command running
Results
failed
Rule status
Ruleid: SA000005, Rulename: SA000005, Status: False
Verify Rules command completed
```

**Expected behavior**
pass verifyrules

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - ApplicationInspector.CLI 1.4.24+4c95dbd1e2

**Additional context**
I thought 
`"search_in": "finding-region(0,0)" `
means finding additional patterns on the same line where original pattern was found.
Am I right?

**Comment by gfs** [comment]
The correct argument for checking the same line is "same-line".

https://github.com/microsoft/ApplicationInspector/blob/c055aa393bd3eba3bf8c1e97756718f81949f8fc/RulesEngine/Ruleset.cs#L277

**Comment by gfs** [comment]
I removed this limitation in #403 so finding-range(0,0) should work after that merge.
