### ISSUE TITLE
SBOM generation of inspected applications

### ISSUE THREAD

**Issue by cqueern** [microsoft/ApplicationInspector#435]
**Describe the solution you'd like**
Application Inspector recently [added an SBOM gathering task](https://github.com/microsoft/ApplicationInspector/pull/428). That's exciting. Was wondering if beyond gathering its own SBOM, whether Application Inspector functionality could be added that would offer the option to generate an SBOM in [CycloneDX](https://cyclonedx.org/) or [SPDX](https://spdx.dev/) format for the application being inspected?

Perhaps there could be a flag for SBOM generation like:

`-b, --sbom-file-format               Software Bill of Materials (SBOM) file format [cyclonedx|spdx]`

**Comment by gfs** [comment]
@cqueern Thanks for your suggestion.

Microsoft has announced we will be releasing an SBOM generator as open source soon - this is the generator that is currently called by the Application Inspector pipeline. Given that is the case, we do not intend to duplicate the functionality with a parallel implementation in AI. You can read more about the upcoming SPDX generator here: https://devblogs.microsoft.com/engineering-at-microsoft/generating-software-bills-of-materials-sboms-with-spdx-at-microsoft/

If you find that once the generator is released, you will still find value in Application Inspector leveraging the generator as a library it is something that we can pursue implementing.

**Comment by cqueern** [comment]
Makes sense. Thanks @gfs . Will close this Issue and check out the SBOM generator when it's released.
