### ISSUE TITLE
Application Inspector HTML tags aren't showing properly

### ISSUE THREAD

**Issue by scovetta** [microsoft/ApplicationInspector#442]
**Describe the bug**
All of the tag icons are highlighted, but none are clickable. There is a JS error saying that `match.tags` is not defined.

**To Reproduce**
1. Run the default CLI / analyze against a directory.
2. Open output.html
3. Click Summary.

**Expected behavior**
Icons should be clickable.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: [687cf00](https://github.com/microsoft/ApplicationInspector/commit/687cf00e8496a08e4ea045c0e73294531428ed9e)

**Additional context**

**Comment by gfs** [comment]
Fixed in 1.5-beta.
