### ISSUE TITLE
HTML Report: File listing line number does not update

### ISSUE THREAD

**Issue by scovetta** [microsoft/ApplicationInspector#443]
**Describe the bug**
When you click a new file to view the contents of (via Summary / click icon), the "Line Number: 42" on the bottom of the modal doesn't update.

**To Reproduce**
1. Default HTML report, view summary, click icon, click finding tag, change to a different file.

**Expected behavior**
Line number should update when a new file is clicked.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: [687cf00](https://github.com/microsoft/ApplicationInspector/commit/687cf00e8496a08e4ea045c0e73294531428ed9e)

**Comment by gfs** [comment]
Fixed in 1.5-beta.
