### ISSUE TITLE
AI HTML report requires some CDN assets

### ISSUE THREAD

**Issue by Eldadc** [microsoft/ApplicationInspector#450]
After Running scan with CLI command , Report created successfully.
Report - Feature Group Links are not been displayed , Missing image and link on the list.
Reproduced on Edge and Chrome.

Thanks

**Comment by gfs** [comment]
Hey @Eldadc,

Can you provide a screenshot of the elements that aren't displaying correctly?

Is this only with a specific set of source code or with any source code?

What version of app inspector are you using?

If a 1.4 version, Does this issue also occur with the 1.5 beta release?

Thanks

**Comment by Eldadc** [comment]
Hi,

I am working in offline network , so I have issue sending screen shots.

1. 1.4.29

Thanks

**Comment by gfs** [comment]
Understood. Sorry you're encountering an issue with the HTML report. Thanks for the version number.

I will try to reproduce tomorrow in an offline environment.

I have a theory that there is a reference to a style sheet or other resource required for the page to function properly that is a ref to an online resource and not bundled. If this is the case it should be an easy fix, just to download that resource and bundle it.

Caveat: I did not originally write the HTML format for AI, and it is relatively complex, but the design intent is that the HTML report is standalone and does not require online resources. We don't run any service or anything that is performing work - all the analysis is done locally and already compiled into the HTML file.

**Comment by gfs** [comment]
I was unable to get to this today but I should have time tomorrow, or at the latest EOW to reproduce the issue and develop a fix.

**Comment by gfs** [comment]
I have investigated this today and identified the source of the issues.

1. There are a number of js files that are loaded from cdns
2. There are a number of css files that are loaded from cdns
3. The project uses FontAwesome - so one of those js files also tries to dynamically fetch woff2 files.

I was able to refactor the code so 1 and 2 are included, but I encountered some issues with some of the javascript when embedded this way and the woff2 files cannot be directly embedded in the html from what I have been able to find, so I think it might be a dead end to make a standalone single .html file.

I'll have to look deeper into this to determine what to do next. Due to the complexity of the html report, I think it is simpler to remove the output format entirely and replace it with a reader mode in AI that run locally and parse the json or sarif result and provide a similar format to the current html output.

**Comment by Eldadc** [comment]
Hi,

Thanks so much on your determination and efforts to help us !
So basically I will set the output format to JSON or SARIF file and display i with other third party viewer.
Do you support SARIF output format ? 

Thanks

**Comment by gfs** [comment]
Yes, application inspector supports both a proprietary json format and standard sarif output that can be viewed with the tool of your choice. Use the -f json or -f sarif argument to analyze. 

Note: when using -f sarif and the output is printed to stdout unless you specify a -o location for the output file.

For example:

`Appinspector analyze -s path/to/src -f sarif -o path/to/output.sarif`

**Comment by Eldadc** [comment]
Hi,

I have managed to run application with sarif output , sarif was created successfully, but the content is missing , there only issues regrading remarks , all other issues are missing , of course the file is very small .
On the other hand the HTML output file has significantly more content if I open it with text editor.

Thanks

**Comment by gfs** [comment]
Sorry, I’m not sure what you mean.

* Are you using custom rules or default rules?
* If you’re using default rules, what rule identifiers are present in the html but not sarif?
* if you’re using custom rules, is there any pattern to the qualities of the rules that have matches and other that don’t between the two outputs?
* What is the full set of arguments you’re using
for both sarif and html? I don’t need the paths.
* What do you mean by “remarks”? The sarif output should have records for all the matches, with their associated tags. Things that are not considered matches (metadata) are not included in the sarif at this time, but some of that is used in the html report, what aspect of the HTML report are you missing?

**Comment by Eldadc** [comment]
Hi,

Yes I am running simple CLI command with default rules.
Command:
applicationInspector.CLI.exe analyze -s <path to code> -f sarif -o <path to sarif report .sarif>

The sarif have been created but with just issues regrading CodeHygiene  "ToDo" remarks .
The HTML file has of course a lot of issue in their content.

Thanks

**Comment by gfs** [comment]
Thanks. I'll take a look soon - I have time set aside this week for app inspector. 

One more thing, if you run the json report are the issues you expect to see present? The json report should be essentially a raw dump of the result object.

**Comment by Eldadc** [comment]
Hi,

No ,Looks like same results like sarif.
Question ,  Sarif \ JSON should contain all data regrading coding features of first or third party software components ?

**Comment by gfs** [comment]
We are looking to replace the html report with a blazor interface that can parse and display the json report (see #2).

I don't have a timeline yet for when that work will be done, but it will be designed to work without any cdn assets.
