### ISSUE TITLE
AppInspector doesn't run after install

### ISSUE THREAD

**Issue by fcbrandon** [microsoft/ApplicationInspector#455]
**Describe the bug**
Attempted an install of AppInspector on a Macbook Pro 16 M1, Monterey 12.1. The install seemed to go smoothly, but I get the following error when I attempt to run it:
`A fatal error occurred. The required library libhostfxr.dylib could not be found.`

**To Reproduce**
1. `brew install dotnet`
2. `dotnet tool install --global Microsoft.CST.ApplicationInspector.CLI`
3. `appinspector`

**Expected behavior**
Appinspector should run; I assume it'll give me the help?

**Operating Environment (please complete the following information):**
 - Application Inspector Version: Unknown - whatever `dotnet` is installing.
 - OS: Mac OS 12.1
 - .Net: 6.0.104

**Additional context**
Full error is here:
```
A fatal error occurred. The required library libhostfxr.dylib could not be found.
If this is a self-contained application, that library should exist in [/Users/branca/.dotnet/tools/.store/microsoft.cst.applicationinspector.cli/1.4.29/microsoft.cst.applicationinspector.cli/1.4.29/tools/net6.0/any/].
If this is a framework-dependent application, install the runtime in the global location [/usr/local/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet].

The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=arm64&rid=osx.12-arm64&apphost_version=6.0.4
  ```

Thanks!

**Comment by gfs** [comment]
Thanks for the report. I'll take a look next week.

Since you are not specifying a version you should be getting the latest 1.4. 

You could try 1.5.5-beta to see if  the issue is also present in 1.5 (I'll be checking this as well next week, but I only have an Intel Mac not an M1 - unsure if that may be the issue).

https://www.nuget.org/packages/Microsoft.CST.ApplicationInspector.CLI/1.5.5-beta

**Comment by fcbrandon** [comment]
Awesome - thanks.  How do I install a specific version?

**Comment by gfs** [comment]
For a specific version specify with the --version argument. 

For example:
`dotnet tool install --global Microsoft.CST.ApplicationInspector.CLI --version 1.5.5-beta`

**Comment by gfs** [comment]
From the error message it looks to me like the runtime is not properly installed and this is not specifically an application inspector issue. 

Have you tried running the installer from the link in the error rather than using the homebrew installer?

**Comment by fcbrandon** [comment]
Good call - that worked. Seems like `brew` install of dotnet doesn't work great for this.

To clarify what I did, here's the steps:
1. `dotnet tool uninstall --global Microsoft.CST.ApplicationInspector.CLI`
2. `dotnet tool install --global Microsoft.CST.ApplicationInspector.CLI --version 1.5.5-beta`
3. `https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=arm64&rid=osx.12-arm64&apphost_version=6.0.4`
4. `https://go.microsoft.com/fwlink/?linkid=2063366`

Fwiw, I uninstalled the beta, then went back and installed the main distro, and that seems to have worked fine:
```
~ % appinspector
ApplicationInspector.CLI 1.4.29+a697529398
© Microsoft Corporation. All rights reserved.

ERROR(S):
  No verb selected.

  analyze        Inspect source directory/file/compressed file (.tgz|zip) against defined characteristics

...
```

Thanks for the help Gabe - can't wait to get back to playing with this! 👍

**Comment by gfs** [comment]
Awesome. Glad you're unblocked. Let me know if you hit any other issues.

The brew documentation for dotnet mentions an additional step you need to take to set the path. But this might not be apparent from the command line.

It also looks like the brew is a possibly a couple versions behind. If I'm interpreting the definition correctly. I saw 6.0.1 in the json definition, but I think 6.0.4 is the latest.
