### ISSUE TITLE
No results, empty output.html file

### ISSUE THREAD

**Issue by scovetta** [microsoft/ApplicationInspector#461]
**Describe the bug**
When no findings are generated, an empty output.html is generated.

**To Reproduce**
1. Create an empty directory, add a single file called "test.c".
2. Run Application Inspector (CLI).
![image](https://user-images.githubusercontent.com/732166/174953113-d3acbcb4-d787-4110-88ce-557f6fab8247.png)

4. See the output file is empty.

![image](https://user-images.githubusercontent.com/732166/174953158-9a01fc0e-7c7c-45ea-81ac-a36b5879641d.png)

**Expected behavior**
The output message from the CLI should probably just say, "No results were generated" and the file shouldn't be overwritten (if it exists). The output error level should probably be non-zero too.

**Operating Environment (please complete the following information):**
 - Application Inspector Version: [from `appinspector -v`]
ApplicationInspector.CLI 1.5.10+0f96c5869d
 - OS: [e.g. Windows 11 21H2 22000.613, MacOS 13.0.1, Linux Ubuntu 20.04]
Windows 11

**Comment by gfs** [comment]
Good catch. I noticed this behavior today as well. The issue is the html report generation logic checks for a "success" status - which excludes "no matches" and no-ops if it has no success.

**Comment by gfs** [comment]
I have an idea for a fix but it needs testing as I'm not sure what the html report generator does if it has no matches. Will take a look tomorrow.
