### ISSUE TITLE
Empty Output.html

### ISSUE THREAD

**Issue by ussenkula** [microsoft/ApplicationInspector#469]
I dont unerstand why sometimes when I scan my python project (as folder with my main.py, all libraries and etc) it gives me an empty output.html and "0 matches, X files skipped out of X files". It seems that it doesnt think my code needs to be analized but I dont know why

**Comment by gfs** [comment]
Hi @ussenkula,

Can you provide the version of application inspector you're using? Have you tried with the latest (1.5.13)?

What arguments are you providing?

Do you only see this with python projects?

Files being skipped may mean either that their extensions don't match an expected format for AI or that they match one of the exclusion glob filters.

https://github.com/microsoft/ApplicationInspector/blob/9f33c68fd1f5ce71f575330c2b8b4b8c3e8d27a3/AppInspector.CLI/CLICmdOptions.cs#L59
