### ISSUE TITLE
ERROR when running the Application Inspector in WSL 2

### ISSUE THREAD

**Issue by MarkLee131** [microsoft/ApplicationInspector#484]
**Describe the bug**

**To Reproduce**

1. Download the OWASP Benchmark by `git clone https://github.com/OWASP-Benchmark/BenchmarkJava`.
2. Change the directory to the benchmark: `cd BenchmarkJava`.
3. Run ApplicationInspector with `appinspector analyze -s ./`.
4. See the error.

**Expected behavior**

Get the result file from the benchmark.

**Screenshots**
![屏幕截图 2022-07-30 235422](https://user-images.githubusercontent.com/38575222/181926201-f834b450-9b69-45a6-a94f-d142dbfcfc5e.png)

**Operating Environment (please complete the following information):**

 - Application Inspector Version: ApplicationInspector.CLI 1.5.20+3790d0a4cb
 - OS: WSL 2 on Windows 10 [version 10.0.19044.1826].
 - .NET version: 6.0.302

**Comment by MarkLee131** [comment]
I tried on the Linux system and found that there is no error on it. I think maybe this issue is caused by the WSL 2. So try not to use WSL to run SAST tool···

**Comment by gfs** [comment]
Thanks for the report. This seems like it's a WSL issue but I'll see if I can find a resolution or at least a record that this is a known bug in .net or wsl.

**Comment by gfs** [comment]
There are a few options you can try as a workaround in the meantime:

1. The AI program should behave the same on Linux and windows. Since you're running WSL you could just run it in your windows context with the same source code. 
2. You could try to install the .NET sdk inside WSL and then use the .NET tool version with "dotnet tool install" https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu
3. It sounds like it works on your native Linux install as well.

**Comment by MarkLee131** [comment]
Thanks for your reply!
It is necessary to mention that the second method does not seem to be effective because it is the method I used to install and use in the beginning.

**Comment by gfs** [comment]
Got it. Thanks for the extra info.

**Comment by gfs** [comment]
I checked out the codebase you linked and cannot reproduce this on my machine, with WSL 2 and the default ubuntu image.

![image](https://user-images.githubusercontent.com/98900/182293913-53273b3d-564b-49c7-9ca1-2fb1d1331779.png)

**Comment by gfs** [comment]
I noticed you were scanning data in the windows drive, I also tried that and got identical results to above.
