### ISSUE TITLE
Support for YML Path Patterns

### ISSUE THREAD

**Issue by gfs** [microsoft/ApplicationInspector#490]
As a follow up from #420 it would be nice to also support YAMLPath. I haven't found a C# library that has the functionality we need yet but YamlDotNet has an open feature request for this functionality (https://github.com/aaubry/YamlDotNet/issues/333).

**Comment by valinha** [comment]
Maybe a solution would be to convert the yml to json and then apply json-path to it. Clearly it is important to narrow down the scope of the rules very much.

**Comment by gfs** [comment]
> Maybe a solution would be to convert the yml to json and then apply json-path to it. 

I did consider this earlier and while technically possible to do the conversion, this means you don't get the information about where in the file the match occurred - you'd be able to identify in the converted JSON where it occurred - but there's no mapping from that back to where the finding is the YML file.

**Comment by gfs** [comment]
YAMLPath is specified here: https://github.com/wwkimball/yamlpath/wiki/Segments-of-a-YAML-Path it might be possible to build this as extension methods on YamlMappingNode from YamlDotNet.

**Comment by gfs** [comment]
This is live in 1.6.22. If you encounter any issues please let me  know with the specific query you're having trouble with.
