### ISSUE TITLE
How to display all child elements in inspect tool?

### ISSUE THREAD

**Issue by Arulpriya** [microsoft/ApplicationInspector#502]
Hi Team,

We have a custom control like datagrid that supports ui accessibility by deriving the IRawElementProviderFragmentRoot, ISelectionProvider and IScrollProvider interfaces. When we tried to automate our custom control using inspect tool, Only 12 cell elements are updated in the Inspect tool pane whereas the grid has 60 cells (15 rows and 4 columns). In our UIPRovider class we have a method that returns the IRawElementProviderFragmentRoot of each cell based on the accessibilityName and id. It returned properly when we debug but it is not reflected in the inspect tool. Below is the code that we are used to update the element value for each cells. While debugging, we noticed that the element is returned as null in inspect window for a specified cell since the GetObject message was not invoked for that cell in WndProc method of our custom control. Can you please suggest a solution to update all the grid cell elements in inspect window?

`public object GetPropertyValue(int propertyId)`
`{`
`    GridRangeInfo spannedRange = GridRangeInfo.Empty;`
`    if (this.Grid != null)`
`    {`
`        Grid.Model.GetSpannedRangeInfo(Info.CellIdentity.RowIndex,(Info.CellIdentity.ColIndex, out spannedRange)`
`    }`
`if (propertyId == AutomationElementIdentifiers.NameProperty.Id /*|| propertyId == 30020*/)`
         `   {`
          `     if (spannedRange.RangeType != GridRangeInfoType.Empty)`
        `        {`
          `          return "GridCell_R" + spannedRange.Top + "_C" + spannedRange.Left;`
         `       }`
           `     return "GridCell_R" + this.Info.CellIdentity.RowIndex + "_C" + this.Info.CellIdentity.ColIndex;`
 `           }`
`}`
<img width="1748" alt="gridelement" src="https://user-images.githubusercontent.com/32356523/185562788-a3b1717c-2228-47f7-88cc-7e7f89b96df4.png">

Thanks in advance,
Arulpriya R

**Comment by gfs** [comment]
Hi @Arulpriya,

This repository is for the Application Inspector code scanning tool, I'm not familiar with the tool you're using here.
