### ISSUE TITLE
Support .NET 7 Non-Backtracking Regex as option

### ISSUE THREAD

**Issue by gfs** [microsoft/ApplicationInspector#510]
Provide an option flag on the RuleProcessor to use non backtracking regex.

https://devblogs.microsoft.com/dotnet/regular-expression-improvements-in-dotnet-7/#backtracking-and-regexoptions-nonbacktracking

**Comment by dbalikhin** [comment]
I'm trying to understand how analyzer actually works and it simply goes to OAT project. 
OAT does actual regex search. It has a couple of parameters: `i` and `m`.
https://github.com/microsoft/OAT/blob/main/OAT/Operations/RegexOperation.cs#L51

It looks like we can set these params through pattern's modifiers (at least I can see `i` here).
    "patterns": [
      {
        "pattern": "authorize|authorized|authorization|isauthorized",
        "type": "regexword",
        "scopes": [
          "code"
        ],
        "modifiers": [
          "i"
      ...
      }

Are you talking about supporting a new modifier to let OAT know to use nonbacktracking?
Or it is a parameter to CLI?
Or both?

**Comment by gfs** [comment]
So application inspector uses OAT to execute rules - but the operation delegates are defined in the app inspector code base, I don't believe this change requires changing OAT. 

See this for the regex operation:
https://github.com/microsoft/ApplicationInspector/blob/505942298a290aad129c6e26c6b748c80b94ecf5/AppInspector.RulesEngine/OatExtensions/OatRegexWithIndexOperation.cs#L80

This would require changing the method that converts the app inspector deserialized rule to oat rule (below) and then modifying the operation delegate from above to respect the new parameter. 

https://github.com/microsoft/ApplicationInspector/blob/505942298a290aad129c6e26c6b748c80b94ecf5/AppInspector.RulesEngine/AbstractRuleSet.cs#L75

**Comment by gfs** [comment]
That said. I thought of this option making more sense as a parameter to the cli/lib to apply to all patterns used in a run - rather than something specified in a per pattern basis. So how to do that may require a bit more thought as to how to get that parameter to the right place for when the regexes are instantiated.

**Comment by gfs** [comment]
One way to do this could be to add an option to the analyze options and cli analyze options to enable nonbacktracking and pass that to the rule set or have a property to set in the abstract rule set to cause the oat rule generation to pass the non backtracking parameter. 

Another way would be to, after the rules are deserialized to app inspector rules but before they are converted to oat rules inject the option there and then have the conversion method check for that option as well as `i` and `m`.

**Comment by gfs** [comment]
To be more specific: See line 242 for 265 to see the instantiation of the appinspector oat regex operator, which can be either a regex or a "regexword". Regex word requires the pattern have white space around it so it won't match just part of a word. 

https://github.com/microsoft/ApplicationInspector/blob/505942298a290aad129c6e26c6b748c80b94ecf5/AppInspector.RulesEngine/AbstractRuleSet.cs#L242

Historical context: app inspector doesn't use the default regex operator from OAT, originally primarily because it needs the index of the match to be returned in order to indicate the location of the match. Instead it defined custom operations which OAT calls when appropriate based on the rule being executed. 

Returning the index is not built into OAT, as OAT was derived from the AttackSurfaceAnalyzer (ASA) rules engine (it is now a thin shim that adds some property parsing delegates to handle ASA specific types: https://github.com/microsoft/AttackSurfaceAnalyzer/blob/ff468b93c28d91b0f3f70bed122038656623540b/Lib/Utils/AsaAnalyzer.cs#L48) ASA does use the default OAT regex (and its rule format is basically identical to the oat rule format: https://github.com/microsoft/AttackSurfaceAnalyzer/blob/ff468b93c28d91b0f3f70bed122038656623540b/Lib/Objects/AsaRule.cs#L7) and other operations, as it does not use the index of the finding.

**Comment by dbalikhin** [comment]
Wow, a lot of info, thanks.
It makes sense now.

**Comment by gfs** [comment]
Hope that extra context helps. Just let me know if you have additional questions about how all the pieces fit together here.

**Comment by dbalikhin** [comment]
I'm thinking of creating `EnableRegexBacktracking` flag instead of `NonBacktracking`.
Rationale: In the future, I expect nonbacktraking to be a default option.

If you need to enable BackTracking globally, use  `EnableRegexBacktracking` or just `b` flag, which will enable it for the whole ruleset. 
If you need to enable BackTracking for specific individual rules, use a new pattern modifier - `b` and leave a global flag untouched.

Transition period: EnableRegexBacktracking is `ON` by default, so if you explicitly didn't disable it, it will work as before.

Future: EnableRegexBacktracking is `OFF` by default. You need to enable it explicitly. 
If some rules don't work properly/faster with NonBacktracking, they can be overridden with a local pattern modifier.

For .NET<7, it won't do anything for the obvious reason.

**Comment by gfs** [comment]
I'd prefer to keep the 1:1 relationship with the arguments to the Regex api for 2 reasons.

1. For parsing from the command line a boolean value is interpreted as the presence or not of the flag. With commandlineparser, I believe, there is no way to set a Boolean false with a from the command line if it defaults to true. This would mean - if this logic were on the lib but inverted on the cli so it could function - needing an inversion of the Boolean before passing to the lib options. 
2. This creates an inversion of expectation from how .NETs implementations take the parameter, which is an option you have to provide to the instance of regex to disable backtracking. Currently we have a 1:1 map between adding arguments to a regex config and setting for ignore and multi line. This change would mean always including the .NET argument unless the parameter is set. I don't expect that .NET will change the API surface so I'd expect that nonbacktracking will always remain non-default. 

I think it makes sense to implement it as a 1:1 map with the regex api (especially for the parameter in the rule file) for now. In addition I am not sure about a transition to making it the default in the near term - per the .NET team there's a fair few features that won't work with the non backtracking engine.

**Comment by gfs** [comment]
Perhaps we can address the issue of using non backtracking by default but breaking existing functionality with an addition to the rule validator? I wonder if there is an (existing) way to check if the pattern requires the backtracking engine directly from the Regex api.

**Comment by dbalikhin** [comment]
I can check the behavior when a regex requires backtracking.
Changing a default option is relatively cheap, so I don't mind having breaking as the default one.

**Comment by gfs** [comment]
@dbalikhin I tested in csharprepl, and it looks like if you pass a regex that the non-backtracking engine doesn't support you get `NotSupportedException`.

What are you thoughts? Rule validation is run automatically when using custom rules, so we can detect this during the validation step by attempting to construct the regex (I believe this already happens we may just need another case to capture this specific error).

Some options if a Regex is provided in NonBacktracking mode but the regex requires backtracking,
1. "NonBacktracking" is best effort. catch the exception and construct the regex with backtracking instead, warn the user that this has occurred and how to modify the rule to work without the warning.
2. Fail validation. Output an error message with other validation errors that instructs the user how to modify the rule and/or specify the correct cli parameter.

My inclination is to go with option 1 and modify this catch block to retry `_ = new Regex(searchPattern.Pattern);`, in a second try.

https://github.com/microsoft/ApplicationInspector/blob/505942298a290aad129c6e26c6b748c80b94ecf5/AppInspector.RulesEngine/RulesVerifier.cs#L140-L160

**Comment by dbalikhin** [comment]
Yes, it will show `NotSupportedException`, e.g., `System.NotSupportedException: 'RegexOptions.NonBacktracking is not supported in conjunction with expressions containing: 'positive lookahead (?= pattern) or positive lookbehind (?<= pattern)'.'`

I like option `1` too. I just need some time to work on the issue :)

**Comment by gfs** [comment]
Okay, sounds good. I did a little cleanup of how the modifiers are parsed in the linked PR (#526), that will also ensure that the rules are validated with the specified modifiers.
