### ISSUE TITLE
Excerpt extracted from yaml rule using yaml path is not correct.

### ISSUE THREAD

**Issue by ismadirolas** [microsoft/ApplicationInspector#511]
**Describe the bug**
Using a rule with yamlpath, the excerpt returned inside match is always the beginning of the file.

**To Reproduce**
With file:
```
test:
  test1:
    - something
    - other
  test2: true
  test3:
    test:
      other:
        - other1:
          property1: 1
          property2: 2
      tested: ok
```

Using rule:
```
   [
    {
      "name": "Yaml test",
      "id": "00000001",
      "applies_to_file_regex": [
        "test.yml"
      ],
      "tags": [
        "MyTest"
      ],
      "severity": "moderate",
      "patterns": [
        {
          "pattern": "ok",
          "ymlpaths": ["/test/test3/test/tested"],
          "type": "string",
          "scopes": [
            "code"
          ],
          "modifiers": [
            "m"
          ],
          "confidence": "high"
        }
      ]
    }
]
```

The match returned:

```
      {
        "ruleId": "00000001",
        "ruleName": "Yaml test",
        "ruleDescription": "",
        "tags": [
          "MyTest"
        ],
        "severity": "Moderate",
        "pattern": "ok",
        "confidence": "High",
        "type": "String",
        "language": "yaml",
        "fileName": "./paas/config_paas/test.yml",
        "sample": "te",
        "excerpt": "test:\n  test1:\n    - something\n    - other\n",
        "startLocationLine": 1,
        "startLocationColumn": 0,
        "endLocationLine": 1,
        "endLocationColumn": 2
      }
```

Note that "test:\n  test1:\n    - something\n    - other\n" doesn't even contains the matched string.

**Expected behavior**
As with the other rules, the excerpt should contains the matched string, and lines before and after the match.

**Operating Environment (please complete the following information):**
 - Application Inspector Version: 1.6.19
 - OS: Linux Ubuntu 22.04

**Comment by gfs** [comment]
Thanks for the report. I can confirm there's an issue.  It looks like the appropriate offset for the start of the actual match `ok` is not being added. I think this will be an easy fix.

**Comment by gfs** [comment]
Fixed coded and tests are running on the PR now. I've added a better test case based on your bug report sample to ensure that the Index of the found match is correct going forward.
