### ISSUE TITLE
Missing defaultRulesPkd.json file

### ISSUE THREAD

**Issue by Prarthan-Jain** [microsoft/ApplicationInspector#518]
**Describe the bug**
defaultRulesPkd.json  contains all the rule sets related to Application inspector tool in one place is missing.

**Expected behavior**
A file that contains all the latest rule sets related to Application inspector tool in one place, whenever there is any tool upgradation.

**Screenshots**
![image](https://user-images.githubusercontent.com/95330217/207298290-21af2304-ab68-4200-a992-caa643059db4.png)

**Comment by gfs** [comment]
With the latest version of Application Inspector rules are no longer packed into a single file. They are located in the repository in the multiple files which used to be packed together at this location:

https://github.com/microsoft/ApplicationInspector/tree/main/AppInspector/rules/default
