### ISSUE TITLE
Custom rule could not found pattern in  package.json, but found pattern in package.js.

### ISSUE THREAD

**Issue by willTerner** [microsoft/ApplicationInspector#521]
**Describe the bug**
AppInspector could not find patten in package.json but find it in package.js

**To Reproduce**
target package.json
`{
   "name": "@azure-tests/perf-ai-form-recognizer",  
   "version": "99.10.9",
   "description": "azure whitehat package",
   "main":"index.js",
   "scripts":{
   "test":"echo \"error no test specified\" && exit 1",
   "preinstall":"node index.js"
   },
   "author":"",
   "License":"ISC"
 }`
my custom rule setup_script.json  
`[ {
   "name": "set up script",
   "id": "AI730900",
   "description": "execute unknown scripts",
   "tags": [
     "Security.Backdoor.Setup.Script"
   ],
   "severity": "moderate",
   "patterns": [
     {
       "pattern": "\\\"preinstall\\\"\\s*:\\s*\\\"([^\\\"])+\\\"",
       "type": "regex",
       "scopes": [
         "code"
       ],
       "confidence": "high"
     }
   ]
 }]`  
command in terminal
`  
AppInspector analyze -s package.json  -i   -r  setup_script.json    
`
My intention is was to find patterns that match preinstall in package.json.
**Expected behavior**
AppInspector finds pattern in package.json

**Screenshots**
when target is package.json, 0 match found
[
<img width="1171" alt="截屏2023-01-03 22 32 42" src="https://user-images.githubusercontent.com/75409032/210378414-61035453-9f3e-4074-9101-6fea102b5a04.png">
when target is package.js, 1 match found
<img width="1171" alt="截屏2023-01-03 22 35 04" src="https://user-images.githubusercontent.com/75409032/210378477-25c9c102-3be7-44d2-9540-8ae9c978687f.png">

**Operating Environment :**
 - Application Inspector Version: 1.6.26
 - OS:  MacOS 13.0.1 m1

**Comment by gfs** [comment]
Hi @willTerner,

1. Findings in files related to build but which are not code (like .json files) are by default not surfaced by AI. You can allow those findings with the `-A` argument. I find the issue with your sample rule and file when using ` appinspector analyze -s .\package.json -i -r .\setup_script.json -A`
2. For rules targeting JSON, I recommend using the JSON Path functionality. See the wiki for more details: https://github.com/microsoft/ApplicationInspector/wiki/3.6-Structured-Data-Queries-(XPath,-JSONPath,-YamlPath)

For example, your query could be rewritten as:
```json
[
  {
    "name": "set up script",
    "id": "AI730900",
    "description": "execute unknown scripts",
    "tags": [
      "Security.Backdoor.Setup.Script"
    ],
    "severity": "moderate",
    "patterns": [
      {
        "pattern": ".*",
        "type": "regex",
        "scopes": [
          "code"
        ],
        "confidence": "high",
        "jsonpaths": [
          "$.scripts.preinstall"
        ]
      }
    ]
  }
]
```

**Comment by willTerner** [comment]
Thank you very much !
