### ISSUE TITLE
Add detection for common enterprise SaaS integrations

### ISSUE THREAD

**Issue by cqueern** [microsoft/ApplicationInspector#552]
Application Inspector already identifies integrations with Cloud Services such as Azure, AWS, and GCP.  

Another interesting characteristic of an application is whether it integrates with one or more common enterprise SaaS services such as ServiceNow, Salesforce, or Workday. Would be very helpful if App Inspector did so because it would allow security and developer teams to better manage such groups of applications in a broader portfolio of enterprise software.  

Perhaps the identification of such integrations might be represented in the Feature Groups -> Cloud Services output.

**Comment by gfs** [comment]
@cqueern Thanks for the suggestion. I think this would be a good improvement to the rules.

**Comment by gfs** [comment]
@cqueern I added some simple detections for the first party API endpoints for these services and they should appear in the feature groups portion of the HTML report as well. Let me know if you encounter any issues with these (with the examples of what it should/should not detect) or have additional suggestions here.

**Comment by cqueern** [comment]
Thanks very much @gfs . Will play with it and share any thoughts. Much appreciated!
