### ISSUE TITLE
Wiki Update with new features and supported languages

### ISSUE THREAD

**Issue by jwgarrett** [microsoft/ApplicationInspector#566]
**Is your feature request related to a problem? It seems the wiki is outdated. https://github.com/microsoft/ApplicationInspector/wiki

**Describe the solution you'd like**
Please update with the currently supported languages such as terraform etc.

**Describe alternatives you've considered**
One could look at the code and find the answers, but a wiki review would be quick quick :-)

**Comment by gfs** [comment]
@jwgarrett 

Thanks for the feedback. 

I've updated the wiki page (https://github.com/microsoft/ApplicationInspector/wiki/3.4-Applies_to-(languages) to match the langauges specified in languages.json in the repo. 

The title of the issue mentions documentation is missing for some features, are there any other features you've identified which need additional documentation?

**Comment by jwgarrett** [comment]
The only other part of this request is to describe the application features which hopefully could be done programmatically https://github.com/microsoft/ApplicationInspector/wiki#core-features

**Comment by gfs** [comment]
@jwgarrett 

That section still looks accurate to me but I'm open to suggestions if I've misunderstood the critique. I'm not sure how that could be generated programmatically as its a description of high level objectives not code flows. 

Features in the sense of ways to use the application are covered in other sections of the wiki like: https://github.com/microsoft/ApplicationInspector/wiki/1.-CLI-Usage

**Comment by jwgarrett** [comment]
Agreed and thanks for pointing me in the right direction.

**Comment by gfs** [comment]
Glad to hear it. If you notice any other issues please let me know and I'll work to address them. Thanks again for your feedback.
