### ISSUE TITLE
Update CLI Usage documentation to include instructions on how to update Application Inspector

### ISSUE THREAD

**Issue by cqueern** [microsoft/ApplicationInspector#570]
Was hoping this page:

https://github.com/microsoft/ApplicationInspector/wiki/1.-CLI-Usage

...might be updated to include the command line instructions on how to update Application Inspector to the most recent version. 

Thanks for all your hard work!

**Comment by gfs** [comment]
@cqueern Thanks for the feedback. I've added the command for updating to the Wiki!

**Comment by cqueern** [comment]
Works great. Thanks @gfs!
