### ISSUE TITLE
Some Calls To ShellProgressBar Crash On Google Colab Notebook

### ISSUE THREAD

**Issue by nnWhisperer** [microsoft/ApplicationInspector#575]
**Describe the bug**
When I run the appinspector analyze as described below, [on the public repository](https://github.com/lucgagan/auto-playwright), I receive the following error:

> =[09:42:06 INF] Progress bar is enabled so console output will be suppressed. No LogFilePath has been configured so you will not receive log messages
> 6n2;1H2;1H[09:42:16 ERR] Uncaught exception: ArgumentOutOfRangeException:Length cannot be less than zero. (Parameter 'length').    at System.String.Substring(Int32 startIndex, Int32 length)
>    at ShellProgressBar.StringExtensions.Excerpt(String phrase, Int32 length)
>    at ShellProgressBar.ProgressBar.ProgressBarBottomHalf(Double percentage, DateTime startDate, Nullable`1 endDate, String message, Indentation[] indentation, Boolean progressBarOnBottom, Boolean showEstimatedDuration, TimeSpan estimatedDuration, Boolean disableBottomPercentage, String percentageFormat)
>    at ShellProgressBar.ProgressBar.UpdateProgress()
>    at ShellProgressBar.ProgressBar.Dispose()
>    at Microsoft.ApplicationInspector.Commands.AnalyzeCommand.GetResult() in D:\a\_work\1\s\AppInspector\Commands\AnalyzeCommand.cs:line 1026
>    at Microsoft.ApplicationInspector.CLI.Program.RunAnalyzeCommand(CLIAnalyzeCmdOptions cliOptions) in D:\a\_work\1\s\AppInspector.CLI\Program.cs:line 310
>    at Microsoft.ApplicationInspector.CLI.Program.VerifyOutputArgsAndRunAnalyze(CLIAnalyzeCmdOptions options) in D:\a\_work\1\s\AppInspector.CLI\Program.cs:line 124
>    at Microsoft.ApplicationInspector.CLI.Program.<>c.<Main>b__1_1(CLIAnalyzeCmdOptions cliAnalyzeCmdOptions) in D:\a\_work\1\s\AppInspector.CLI\Program.cs:line 41
>    at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 notParsedFunc)
>    at Microsoft.ApplicationInspector.CLI.Program.Main(String[] args) in D:\a\_work\1\s\AppInspector.CLI\Program.cs:line 40

**To Reproduce**
```
!sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-6.0
  # sudo apt-get install -y dotnet-sdk-8.0
!dotnet --list-sdks
!dotnet --version
!dotnet tool install --global Microsoft.CST.ApplicationInspector.CLI

!export PATH="$PATH:/root/.dotnet/tools"
! ls /root/.dotnet/tools/appinspector
!git clone https://github.com/lucgagan/auto-playwright
!ls -al /content/auto-playwright/src/
!/root/.dotnet/tools/appinspector analyze -s /content/auto-playwright/src/

```
Optionally you may add the following in a new cell and run it before running the appinspector analyze:
```
%%writefile ~/.bash_profile
# Add .NET Core SDK tools
export PATH="$PATH:/root/.dotnet/tools"

```
**Operating Environment (please complete the following information):**
 - Application Inspector Version: ApplicationInspector.CLI 1.9.18+00ad48b230
 - OS: Linux Ubuntu 22.04.3 LTS
 - Dotnet version 6.0.127 but also persists in version 8.0.102(restart and run the notebook by changing the commented out line).

**Comment by gfs** [comment]
This doesn't appear to be an out of memory error - it seems like an issue with the progress bar. I can't reproduce this on a normal terminal in Ubuntu 22.04.3, so this is likely caused by the unique environment you're running in - I'm not familiar with google colab but if it doesn't have an interactive terminal that may not play nicely with the redraws required to render the progress bar. 

Since this seems to be a scripted run, you probably want to disable the progress bar anyway with the `-N` or `--no-show-progress` argument.

**Comment by nnWhisperer** [comment]
Thank you
