### ISSUE TITLE
Emit formatted SARIF

### ISSUE THREAD

**Issue by scovetta** [microsoft/ApplicationInspector#576]
**Is your feature request related to a problem? Please describe.**
The SARIF exported is minified and hard to read. Could we add formatting when we emit?

**Describe the solution you'd like**
It looks like the code to write the JSON is here: https://github.com/microsoft/ApplicationInspector/blob/main/AppInspector.CLI/Writers/AnalyzeSarifWriter.cs#L287

**Describe alternatives you've considered**
We could use jq or something else to parse, but it'd be easier if it started out formatted.

**Additional context**
N/A

**Comment by gfs** [comment]
Sure. Shouldn't be too hard to modify.
