### ISSUE TITLE
Can't analyze paths with spaces in names

### ISSUE THREAD

**Issue by CryptoJones** [microsoft/ApplicationInspector#69]
**Describe the bug**
When trying to analyze source directories with spaces in the names, windows appends double quotes to the beginning and end of the path. 

**To Reproduce**
1. Create a folder with spaces in the name
2. Run AppInspector.exe analyze --source "C:\users\bgates\source\repos\My Badly Named Project\\"
3. See error in log. It is ignoring the double quotes and terminates the string evaluation at the space

**Expected behavior**
Evaluate the project in the badly named directory

**Additional context**
Workaround-- Take the spaces out of the project directory's name

**Comment by guyacosta** [comment]
The issue is with the last trailing backslash in your path.  Remove the last backslash i.e. "C:\users\bgates\source\repos\My Badly Named Project" and it runs.  That last symbol messes up the path because it tells the app or OS to look for another unnamed file or folder after.
