### ISSUE TITLE
Add highlighting of source code sample section for improved visibility

### ISSUE THREAD

**Issue by b-u-g-s** [microsoft/ApplicationInspector#70]
**Describe the bug**
When you navigate a report and click on one of the featured discovered, you get a snapshot of the source code. There is also an hyperlink above the snapshot to the source file.
However, when you click on that link, nothing happens.
It woudl be great if you could click on that link and see the full source code so we get more context.
Also, if the snapshot could be highlgihted in the full source code that would be a bonus.

Regards,
S.

**Comment by guyacosta** [comment]
Selecting the link allows you to navigate which of n files we found the match as there may be several so it just loads the new content and if there is only one you wouldn't see a change.

Yes we want to add highlighting of the sample code section for better viewing.  Thanks.

**Comment by guyacosta** [comment]
Renamed title to match the enhancement request.

**Comment by guyacosta** [comment]
Note the json and text file outputs include the exact line number.

**Comment by guyacosta** [comment]
Adding the line number to the bottom on the dialog was a bit easier and didn't require more dependencies.
