### ISSUE TITLE
Turn this into a dotnet global tool? 

### ISSUE THREAD

**Issue by alexdresko** [microsoft/ApplicationInspector#77]
It would be great if this could be installed as a [dotnet global tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools).

That would remove a lot of the friction required to get up and running with the inspector.

**Comment by sharpninja** [comment]
> It would be great if this could be installed as a [dotnet global tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools).
> 
> That would remove a lot of the friction required to get up and running with the inspector.

An app would be good too.  Save/Load settings/profiles, display output, etc.

**Comment by guyacosta** [comment]
Curious what OS?  Note you can run as AppInspector.exe on Windows.

**Comment by sharpninja** [comment]
It either has to be on the path or you have to always reference.  Both = yuck.
________________________________

**Comment by alexdresko** [comment]
> Curious what OS? Note you can run as AppInspector.exe on Windows.

I'm on Windows.

**Comment by gfs** [comment]
@guyacosta Distributing as a dotnet global tools changes the install procedure (to have applicationinpector.exe available from anywhere) with

`dotnet install -g ApplicationInspector`

@daalcant Can we add this to the pipeline?

**Comment by gfs** [comment]
https://www.meziantou.net/how-to-publish-a-dotnet-global-tool-with-dotnet-core-2-1.htm

**Comment by daalcant** [comment]
In progress.
