### ISSUE TITLE
Add Support for Wildcards in Path or Add option to ignore certain filetypes

### ISSUE THREAD

**Issue by gruselglatz** [microsoft/ApplicationInspector#78]
**Is your feature request related to a problem? Please describe.**
In a big repo with heavy zip files i want to ignore them in the scan.

**Describe the solution you'd like**
-o path\to\source\*.java

or 
--ignore-filetypes .zip .gz

**Describe alternatives you've considered**
deleting the zips before scan --> not practical

**Additional context**
Mainly because the scanner crashes with the Zip too large Error

**Comment by guyacosta** [comment]
Best approach is to write a script to auto generate the output file name based on the input file name or similar.  We do that but haven't seen many tools to it for you automatically.  May consider if enough people request again later.
