### ISSUE TITLE
Processing more then 100%

### ISSUE THREAD

**Issue by gruselglatz** [microsoft/ApplicationInspector#79]
**Describe the bug**
The Processing status shows more then 100%

**To Reproduce**
Run the command seen in the screenshot.

**Expected behavior**
Some work status between 0% and 100%

Or change the Message.

**Screenshots**
![ConEmu64_iIfpEPhbUp](https://user-images.githubusercontent.com/15243394/72737126-3f88f300-3b9f-11ea-999d-c458672dc7c5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.0.20

**Comment by AndrewTing** [comment]
A couple spots in AnalyzeCommand.cs, touches the global TotalFiles.
664                 _appProfile.MetaData.TotalFiles = (int)zipFile.Count;
737            _appProfile.MetaData.TotalFiles = GetTarGzFileCount(filename);

This messes the calculation when updating the UI.
I would make the change, but I am verifying permission with my employer that I can do so.

**Comment by guyacosta** [comment]
Does your zip file contain other zipped files?  I've only seen the issue in those cases but would like to confirm.  If it is an OSS package send me the path to download and investigate.
