### ISSUE TITLE
Exception: Cannot access a disposed object.\r\nObject name: 'ZipFile'.

### ISSUE THREAD

**Issue by AndrewTing** [microsoft/ApplicationInspector#81]
**Describe the bug**
Running the tool using parameters "analyze -s <path to files>", I get this error when the tool tries to read a .zip file.

**To Reproduce**
1. Run tool using parameters "analyze -s <path>"
2. Exception will occur on a certain type of zip file.
3. Exception occurs.

**Expected behavior**
Should skip the file, and log the problem.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 (10.0.17763 N/A Build 17763)

**Comment by AndrewTing** [comment]
Looks like a third-party library issue:

Cannot access a disposed object.\r\nObject name: 'ZipFile'.
   at ICSharpCode.SharpZipLib.Zip.ZipFile.GetInputStream(ZipEntry entry)
   at Microsoft.AppInspector.AnalyzeCommand.ProcessZipFile(String filename) in C:\Azure.git\MicrosoftInspector\AppInspector\Commands\AnalyzeCommand.cs:line 673

**Comment by AndrewTing** [comment]
Latest build shows a nice error now, and if you unpack the zip file, the exception goes away.
Can be closed now.

**Comment by guyacosta** [comment]
Yeah I investigated and found the same issue is with the library after attempting several work arounds with it.  Seems to be something with particular zipped files but not obvious what.

**Comment by guyacosta** [comment]
Have replaced the decompression code and am getting better results with "bad" behaving zip files though they can be finicky still per library owners like sharpcompress and sharpziplib.  Try out the new code and release for work done in #105
