### ISSUE TITLE
Ref: #75 ApplicationInspector errors when trying to produce html filetype output

### ISSUE THREAD

**Issue by localacct** [microsoft/ApplicationInspector#86]
**Describe the bug**
A reference to Issue #75 where ApplicationInspector could not produce output file in HTML format

**To Reproduce**
Using the following command line arguments without any output arguments and it will show the error.

````
dotnet /path/to/AppInspector.dll analyze -s file.c
````
````
Runtime error: Could not find a part of the path '/path/to/source_code/files/html/index.html'
````

The tool keeps looking for a non existent index.html file

**Expected behavior**
ApplicationInspector should produce a HTML file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.6 Mojave
 - Browser Google Chrome
 - Version 79.0.3945.130

**Smartphone (please complete the following information):**

**Additional context**

**Comment by guyacosta** [comment]
Fix is checked into source code with commit #92 .  Thanks for reporting.
