### ISSUE TITLE
Package ApplicationInspector as Nuget package to consume in other .NET based projects

### ISSUE THREAD

**Issue by jusso-dev** [microsoft/ApplicationInspector#87]
It would be great to have ApplicationInspector packaged as a Nuget library, so that other .NET projects can consume it's core functionality programmatically.

**Comment by guyacosta** [comment]
We'll get it done -thanks for the suggestion.

**Comment by jusso-dev** [comment]
Hi there, is there anything I can do to get this across the line? I know you are very busy, but I'd to start on some projects that are blocked by not having this. 

I simply just want the Analyze option exposed via an API, with just the source path argument read in.

**Comment by guyacosta** [comment]
@jusso.  Apologies on the delayed response.  Notifications getting put into non-priority folder and didn't see.  Yes the API is already developed in a way that supports being called as a DLL.  I do this myself in other one-off apps.  The barriers to Nuget are simply procedural and signing.  We plan to have this done early next week or you can simply build the project and include the assembly dll's.

**Comment by guyacosta** [comment]
@daalcant please assist.

**Comment by daalcant** [comment]
In progress.
