### ISSUE TITLE
Add a guideline to describe how to compile and use in linux

### ISSUE THREAD

**Issue by gtgbx** [microsoft/ApplicationInspector#88]

**Comment by jusso-dev** [comment]
You would use dotnet build with the required arguments. See this MSF article as to how to do that.

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build

**Comment by guyacosta** [comment]
Yes.  I also added a [build.md](https://github.com/microsoft/ApplicationInspector/blob/master/BUILD.md)
